export const AIChatbot = [
  {
    handle: "flot-ai",
    name: "Flot.ai",
    website: "https://flot.ai/?utm_source=toolify",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169357118260794822.jpg",
    description:
      "Flot.ai: AI Copilot for All Apps and Websites\n\nUse ChatGPT anywhere you type or select, On All Apps and Websites.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "document-assistant",
        name: "Document Assistant",
        name_locales: {
          de: "Dokumentenassistent",
          en: "Document Assistant",
          es: "Asistente de documentos",
          fr: "Assistant de document",
          ja: "文書アシスタント",
          ko: "문서 도우미",
          pt: "Assistente de documentos",
          tw: "文件助手",
          vi: "Trợ lý tài liệu",
          zh: "文档助手",
        },
        tool_count: 187,
      },
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "general-writing",
        name: "General writing",
        name_locales: {
          de: "Allgemeine Schreibarbeit",
          en: "General writing",
          es: "Escritura general",
          fr: "Écriture générale",
          ja: "一般的な文章",
          ko: "일반적인 작성",
          pt: "Escrita geral",
          tw: "一般寫作",
          vi: "Viết chung",
          zh: "常规写作",
        },
        tool_count: 343,
      },
      {
        handle: "paraphraser",
        name: "Paraphraser",
        name_locales: {
          de: "Paraphrasierungsprogramm",
          en: "Paraphraser",
          es: "Paráfrasis",
          fr: "Paraphraseur",
          ja: "パラフレーザー",
          ko: "바꾸기 도구",
          pt: "Paráfrase",
          tw: "改寫工具",
          vi: "Công cụ thay đổi văn bản",
          zh: "改写工具",
        },
        tool_count: 38,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "seo",
        name: "SEO",
        name_locales: {
          de: "SEO",
          en: "SEO",
          es: "SEO",
          fr: "SEO",
          ja: "検索エンジン最適化",
          ko: "검색 엔진 최적화",
          pt: "SEO",
          tw: "搜尋引擎最佳化",
          vi: "tối ưu hóa công cụ tìm kiếm",
          zh: "搜索引擎优化",
        },
        tool_count: 264,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "story-teller",
        name: "Story teller",
        name_locales: {
          de: "Geschichtenerzähler",
          en: "Story teller",
          es: "Cuentacuentos",
          fr: "Conteur d'histoires",
          ja: "語り部",
          ko: "이야기꾼",
          pt: "Contador de histórias",
          tw: "故事講述者",
          vi: "Người kể chuyện",
          zh: "讲故事人",
        },
        tool_count: 126,
      },
      {
        handle: "summarizer",
        name: "Summarizer",
        name_locales: {
          de: "Summarizer",
          en: "Summarizer",
          es: "Generador de resúmenes",
          fr: "Résumeur",
          ja: "要約作成ツール",
          ko: "요약 생성기",
          pt: "Resumidor",
          tw: "摘要產生器",
          vi: "Trình tóm tắt",
          zh: "摘要生成器",
        },
        tool_count: 196,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
      {
        handle: "pricing",
        name: "Pricing",
        options: [
          {
            name: "Paid",
            handle: "paid",
          },
          {
            name: "Free",
            handle: "free",
          },
        ],
      },
    ],
    prices: [],
    month_visited_count: 0,
    collected_count: 7,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "chatpdf",
    name: "Chatpdf",
    website: "https://www.chatpdf.com/?via=toolify",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168197409571939545.jpg",
    description:
      "ChatPDF is a tool that allows users to interact with PDF documents using natural language processing and artificial intelligence. It can extract text from PDFs and feed it to GPT for analysis2. The tool can be used to extract information from large PDF files such as manuals, essays, legal contracts, books, or research papers3.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "resources",
        name: "Resources",
        name_locales: {
          de: "Ressourcen",
          en: "Resources",
          es: "Recursos",
          fr: "Ressources",
          ja: "リソース",
          ko: "자원",
          pt: "Recursos",
          tw: "資源",
          vi: "Tài nguyên",
          zh: "资源",
        },
        tool_count: 67,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "pricing",
        name: "Pricing",
        options: [
          {
            name: "Paid",
            handle: "paid",
          },
          {
            name: "Free",
            handle: "free",
          },
        ],
      },
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: [
      {
        cycle: "120 pages/PDF 10 MB/PDF 3 PDFs/day 50 questions/day",
        price: "$0/mo",
        title: "Free",
      },
      {
        cycle: "2,000 pages/PDF 32 MB/PDF 50 PDFs/day 1000 questions/day",
        price: "$5/mo",
        title: "Plus",
      },
    ],
    month_visited_count: 6029365,
    collected_count: 68,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.18028059737304733,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.6787121851834852,
        },
        {
          title: "Search",
          value: 0.25771062332559524,
        },
        {
          title: "Referrals",
          value: 0.03774841208427635,
        },
      ],
      growth: -1758543,
      growth_rate: -0.2258,
      monthly_visits_mail: 14524,
      monthly_visits_direct: 4092203,
      monthly_visits_search: 1553831,
      monthly_visits_social: 139399,
      monthly_visits_referrals: 227599,
      monthly_visits_paid_referrals: 1808,
      region_monthly_visits: null,
    },
  },
  {
    handle: "hix-ai",
    name: "Hix AI",
    website: "https://hix.ai/?ref=yzqxndr6",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169054819035381052.jpg",
    description:
      "Generate high-quality copies for ads, emails, blogs, and more in seconds with HIX.AI, the most powerful, all-in-one AI writing copilot on the market.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "general-writing",
        name: "General writing",
        name_locales: {
          de: "Allgemeine Schreibarbeit",
          en: "General writing",
          es: "Escritura general",
          fr: "Écriture générale",
          ja: "一般的な文章",
          ko: "일반적인 작성",
          pt: "Escrita geral",
          tw: "一般寫作",
          vi: "Viết chung",
          zh: "常规写作",
        },
        tool_count: 343,
      },
      {
        handle: "paraphraser",
        name: "Paraphraser",
        name_locales: {
          de: "Paraphrasierungsprogramm",
          en: "Paraphraser",
          es: "Paráfrasis",
          fr: "Paraphraseur",
          ja: "パラフレーザー",
          ko: "바꾸기 도구",
          pt: "Paráfrase",
          tw: "改寫工具",
          vi: "Công cụ thay đổi văn bản",
          zh: "改写工具",
        },
        tool_count: 38,
      },
      {
        handle: "seo",
        name: "SEO",
        name_locales: {
          de: "SEO",
          en: "SEO",
          es: "SEO",
          fr: "SEO",
          ja: "検索エンジン最適化",
          ko: "검색 엔진 최적화",
          pt: "SEO",
          tw: "搜尋引擎最佳化",
          vi: "tối ưu hóa công cụ tìm kiếm",
          zh: "搜索引擎优化",
        },
        tool_count: 264,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "summarizer",
        name: "Summarizer",
        name_locales: {
          de: "Summarizer",
          en: "Summarizer",
          es: "Generador de resúmenes",
          fr: "Résumeur",
          ja: "要約作成ツール",
          ko: "요약 생성기",
          pt: "Resumidor",
          tw: "摘要產生器",
          vi: "Trình tóm tắt",
          zh: "摘要生成器",
        },
        tool_count: 196,
      },
      {
        handle: "e-commerce",
        name: "E-commerce",
        name_locales: {
          de: "E-Commerce",
          en: "E-commerce",
          es: "Comercio electrónico",
          fr: "Commerce électronique",
          ja: "Eコマース",
          ko: "전자상거래",
          pt: "Comércio eletrônico",
          tw: "電子商務",
          vi: "Thương mại điện tử",
          zh: "电子商务",
        },
        tool_count: 215,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
      {
        handle: "pricing",
        name: "Pricing",
        options: [
          {
            name: "Paid",
            handle: "paid",
          },
          {
            name: "Free",
            handle: "free",
          },
        ],
      },
    ],
    prices: [],
    month_visited_count: 19250,
    collected_count: 32,
    user_collected: 0,
    traffic: {
      top_region: "HK",
      top_region_value: 0.3944464310670012,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.6501487715922396,
        },
        {
          title: "Search",
          value: 0.19105278875881593,
        },
        {
          title: "Mail",
          value: 0.0842600773322923,
        },
      ],
      growth: -18593,
      growth_rate: -0.4913,
      monthly_visits_mail: 1622,
      monthly_visits_direct: 12515,
      monthly_visits_search: 3678,
      monthly_visits_social: 0,
      monthly_visits_referrals: 1435,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "footagentexam-com",
    name: "footagentexam.com",
    website: "https://www.footagentexam.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454296576858200.jpg",
    description:
      "FootAgentExam.com is your gateway to mastering the FIFA football agent exam with cutting-edge AI-powered learning, interactive quizzes, and time-saving features. Elevate your game in the world of football agents with our revolutionary platform. ⚽️🤖📚",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "education-assistant",
        name: "Education assistant",
        name_locales: {
          de: "Bildungsassistent",
          en: "Education assistant",
          es: "Asistente de educación",
          fr: "Assistant d'éducation",
          ja: "教育アシスタント",
          ko: "교육 조수",
          pt: "Assistente de educação",
          tw: "教育助理",
          vi: "Trợ lý giáo dục",
          zh: "教育助理",
        },
        tool_count: 337,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "infichat",
    name: "Infichat",
    website: "https://infichat.co",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454296365650272.jpg",
    description:
      "A better way to give your customers the support they need without spending a fortune. Increase revenue, keep customers happy and reduce churn!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "customer-support",
        name: "Customer support",
        name_locales: {
          de: "Kundensupport",
          en: "Customer support",
          es: "Soporte al cliente",
          fr: "Support client",
          ja: "カスタマーサポート",
          ko: "고객 지원",
          pt: "Suporte ao cliente",
          tw: "客戶支援",
          vi: "Hỗ trợ khách hàng",
          zh: "客户支持",
        },
        tool_count: 260,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 1653,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: -2232,
      growth_rate: -0.5745,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "interviewspark",
    name: "InterviewSpark",
    website: "https://interviewspark.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454294755321639.jpg",
    description:
      "InterviewSpark is a SaaS e-learning platform and Interview strategist focusing on AI-driven Interview Prep. It conducts realistic mock interviews from a collection of over 1,000 curated questions and offers actionable, data-driven feedback all in real time.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "education-assistant",
        name: "Education assistant",
        name_locales: {
          de: "Bildungsassistent",
          en: "Education assistant",
          es: "Asistente de educación",
          fr: "Assistant d'éducation",
          ja: "教育アシスタント",
          ko: "교육 조수",
          pt: "Assistente de educação",
          tw: "教育助理",
          vi: "Trợ lý giáo dục",
          zh: "教育助理",
        },
        tool_count: 337,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 216,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 216,
      growth_rate: 0,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "gen-expert",
    name: "Gen Expert",
    website: "https://genexpert.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454293895847019.jpg",
    description:
      "Supercharge your chatgpt experience with GenExpert. Unleash the power of customizable GPT models, captivating prompts, and documents with AI auto-completion. Effortlessly create top-notch content, save time, and enjoy ultimate privacy and security.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "general-writing",
        name: "General writing",
        name_locales: {
          de: "Allgemeine Schreibarbeit",
          en: "General writing",
          es: "Escritura general",
          fr: "Écriture générale",
          ja: "一般的な文章",
          ko: "일반적인 작성",
          pt: "Escrita geral",
          tw: "一般寫作",
          vi: "Viết chung",
          zh: "常规写作",
        },
        tool_count: 343,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "code-assistant",
        name: "Code assistant",
        name_locales: {
          de: "Code-Assistent",
          en: "Code assistant",
          es: "Asistente de código",
          fr: "Assistant de code",
          ja: "コードアシスタント",
          ko: "코드 어시스턴트",
          pt: "Assistente de código",
          tw: "代碼助手",
          vi: "Trợ lý mã",
          zh: "代码辅助工具",
        },
        tool_count: 165,
      },
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
      {
        handle: "document-assistant",
        name: "Document Assistant",
        name_locales: {
          de: "Dokumentenassistent",
          en: "Document Assistant",
          es: "Asistente de documentos",
          fr: "Assistant de document",
          ja: "文書アシスタント",
          ko: "문서 도우미",
          pt: "Assistente de documentos",
          tw: "文件助手",
          vi: "Trợ lý tài liệu",
          zh: "文档助手",
        },
        tool_count: 187,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "iwish",
    name: "iWish",
    website: "https://www.iwish.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454292072047090.jpg",
    description:
      "Welcome to the future of seamless tech support. iWish AI is designed to automate tech support and thus transforming your customer experience.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "customer-support",
        name: "Customer support",
        name_locales: {
          de: "Kundensupport",
          en: "Customer support",
          es: "Soporte al cliente",
          fr: "Support client",
          ja: "カスタマーサポート",
          ko: "고객 지원",
          pt: "Suporte ao cliente",
          tw: "客戶支援",
          vi: "Hỗ trợ khách hàng",
          zh: "客户支持",
        },
        tool_count: 260,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 7405,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 6388,
      growth_rate: 6.2812,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "lyras-ai",
    name: "Lyras AI",
    website: "https://lyras.cloud",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454290333965661.jpg",
    description:
      "3x your leads or double staff productivity - conversational AI tools all in one space. Lyras is an AI powered enterprise partner, we help businesses better understand and utilise their traffic.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
      {
        handle: "customer-support",
        name: "Customer support",
        name_locales: {
          de: "Kundensupport",
          en: "Customer support",
          es: "Soporte al cliente",
          fr: "Support client",
          ja: "カスタマーサポート",
          ko: "고객 지원",
          pt: "Suporte ao cliente",
          tw: "客戶支援",
          vi: "Hỗ trợ khách hàng",
          zh: "客户支持",
        },
        tool_count: 260,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "credit-chip",
    name: "Credit Chip",
    website: "https://mobilecredits.app",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454291259399336.jpg",
    description:
      "Credit chips are designed to accept instant person-2-person payments using NFC, URL, QR code, Wearables, MetaMask, Ledger, Trezor, Visa, Mastercard, American Express, Discover, Apple Pay, Google Pay and many more for borderless and instantaneous payments.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "e-commerce",
        name: "E-commerce",
        name_locales: {
          de: "E-Commerce",
          en: "E-commerce",
          es: "Comercio electrónico",
          fr: "Commerce électronique",
          ja: "Eコマース",
          ko: "전자상거래",
          pt: "Comércio eletrônico",
          tw: "電子商務",
          vi: "Thương mại điện tử",
          zh: "电子商务",
        },
        tool_count: 215,
      },
      {
        handle: "finance",
        name: "Finance",
        name_locales: {
          de: "Finanzen",
          en: "Finance",
          es: "Finanzas",
          fr: "Finance",
          ja: "財務",
          ko: "금융",
          pt: "Finanças",
          tw: "財務",
          vi: "Tài chính",
          zh: "金融",
        },
        tool_count: 158,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "chatfolio",
    name: "Chatfolio",
    website: "https://chatfolio.org",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454289566211345.jpg",
    description:
      "Introducing Chatfolio: a chatbot for your portfolio website that can answer any questions about your resume, skills, experience..etc. Upload your resume, add it to your site, and watch how it can instantly enhance your site's experience. Try now for free!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "ai-persona-chat",
    name: "AI Persona Chat",
    website:
      "https://apps.apple.com/us/app/ai-personas-characters/id6456891746",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454288793452491.jpg",
    description:
      "Converse with legendary figures, explore diverse topics, and discover unique personas tailored for every mood. Powered by cutting-edge AI for lifelike conversations. Fresh, exciting, and ever-evolving. Join the chat revolution!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "experiments",
        name: "Experiments",
        name_locales: {
          de: "Experimente",
          en: "Experiments",
          es: "Experimentos",
          fr: "Expériences",
          ja: "実験",
          ko: "실험",
          pt: "Experimentos",
          tw: "實驗",
          vi: "Thí nghiệm",
          zh: "实验",
        },
        tool_count: 49,
      },
      {
        handle: "fun-tools",
        name: "Fun tools",
        name_locales: {
          de: "Spaßwerkzeuge",
          en: "Fun tools",
          es: "Herramientas divertidas",
          fr: "Outils amusants",
          ja: "楽しいツール",
          ko: "재미있는 도구",
          pt: "Ferramentas divertidas",
          tw: "有趣工具",
          vi: "Công cụ vui nhộn",
          zh: "趣味工具",
        },
        tool_count: 197,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
      {
        handle: "language-learning",
        name: "Language learning",
        name_locales: {
          de: "Sprachenlernen",
          en: "Language learning",
          es: "Aprendizaje de idiomas",
          fr: "Apprentissage des langues",
          ja: "言語学習",
          ko: "언어 학습",
          pt: "Aprendizagem de idiomas",
          tw: "語言學習",
          vi: "Học ngôn ngữ",
          zh: "语言学习",
        },
        tool_count: 235,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "App",
            handle: "app",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 118449982,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.24253346927315403,
      top_traffic_sources: [
        {
          title: "Search",
          value: 0.34298605945565247,
        },
        {
          title: "Referrals",
          value: 0.31164588745370364,
        },
        {
          title: "Direct",
          value: 0.23273471611265417,
        },
      ],
      growth: -2523202,
      growth_rate: -0.0209,
      monthly_visits_mail: 1295492,
      monthly_visits_direct: 27567423,
      monthly_visits_search: 40626693,
      monthly_visits_social: 4189658,
      monthly_visits_referrals: 36914450,
      monthly_visits_paid_referrals: 7856266,
      region_monthly_visits: null,
    },
  },
  {
    handle: "chatfuro",
    name: "Chatfuro",
    website: "https://chatfuro.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454287638775970.jpg",
    description:
      "Get your own ChatGPT bots in minutes. Chatfuro helps streamline your chatbots for multiple purposes to ask questions and find information, or embed as a widget on your website to assist your users.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
      {
        handle: "customer-support",
        name: "Customer support",
        name_locales: {
          de: "Kundensupport",
          en: "Customer support",
          es: "Soporte al cliente",
          fr: "Support client",
          ja: "カスタマーサポート",
          ko: "고객 지원",
          pt: "Suporte ao cliente",
          tw: "客戶支援",
          vi: "Hỗ trợ khách hàng",
          zh: "客户支持",
        },
        tool_count: 260,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "ai-interior-room-planner",
    name: "AI Interior Room Planner",
    website: "https://aiinteriorplanner.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454286732704054.jpg",
    description:
      "Transform your living space with InteriorAI Room Planner, your AI-powered interior designer. Snap a photo of your room, and watch AI craft the perfect design. Chat with AI design expert for personalized advice, bringing your vision to life effortlessly.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "design-assistant",
        name: "Design assistant",
        name_locales: {
          de: "Design-Assistent",
          en: "Design assistant",
          es: "Asistente de diseño",
          fr: "Assistant de conception",
          ja: "デザインアシスタント",
          ko: "디자인 어시스턴트",
          pt: "Assistente de design",
          tw: "設計助手",
          vi: "Trợ lý thiết kế",
          zh: "设计助手",
        },
        tool_count: 306,
      },
      {
        handle: "real-estate",
        name: "Real estate",
        name_locales: {
          de: "Immobilien",
          en: "Real estate",
          es: "Bienes raíces",
          fr: "Immobilier",
          ja: "不動産",
          ko: "부동산",
          pt: "Imobiliário",
          tw: "房地產",
          vi: "Bất động sản",
          zh: "房地产",
        },
        tool_count: 66,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "pocket-hansei",
    name: "Pocket Hansei",
    website: "https://pocket.hansei.app",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454283440864750.jpg",
    description:
      "Pocket Hansei is your personal Assistant that offers instant answers by connecting you to trusted, well-sourced topics such as renowned books, research papers, reliable articles, and trending topics. Ask questions, and receive well-researched answers.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "education-assistant",
        name: "Education assistant",
        name_locales: {
          de: "Bildungsassistent",
          en: "Education assistant",
          es: "Asistente de educación",
          fr: "Assistant d'éducation",
          ja: "教育アシスタント",
          ko: "교육 조수",
          pt: "Assistente de educação",
          tw: "教育助理",
          vi: "Trợ lý giáo dục",
          zh: "教育助理",
        },
        tool_count: 337,
      },
      {
        handle: "research",
        name: "Research",
        name_locales: {
          de: "Forschung",
          en: "Research",
          es: "Investigación",
          fr: "Recherche",
          ja: "研究",
          ko: "연구",
          pt: "Pesquisa",
          tw: "研究",
          vi: "Nghiên cứu",
          zh: "研究",
        },
        tool_count: 161,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "cxassist",
    name: "CXassist",
    website: "https://www.cxassist.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454278586226032.jpg",
    description:
      "AI + Email = Productivity. CXassist can automatically manage your inbox for you, intelligently answering emails based on the training data you provide (PDF,txt,csv) giving you hours of productivity back, and providing limitless scale to your business.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "zetabot",
    name: "zetabot",
    website: "https://zetabot.co",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454281771367442.jpg",
    description:
      "Streamline your customer support operations with our advanced AI chatbot. Revolutionize your business and reduce costs by up to 60%. Continuously Learning and Adapting Chatbot Based on Customer Interactions.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "customer-support",
        name: "Customer support",
        name_locales: {
          de: "Kundensupport",
          en: "Customer support",
          es: "Soporte al cliente",
          fr: "Support client",
          ja: "カスタマーサポート",
          ko: "고객 지원",
          pt: "Suporte ao cliente",
          tw: "客戶支援",
          vi: "Hỗ trợ khách hàng",
          zh: "客户支持",
        },
        tool_count: 260,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 17036,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 17036,
      growth_rate: 0,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "chatbros",
    name: "Chatbros",
    website: "https://chatbros.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454283233487276.jpg",
    description:
      "Introducing ChatBros.ai, your personalized AI assistant designed to revolutionize the way you work and achieve your goals. Tailor its skills to match your needs, from lead generation wizardry to any task you desire.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "algomo",
    name: "Algomo",
    website: "https://www.algomo.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454162152400788.jpg",
    description:
      "Say hello to Algomo: a ChatGPT bot designed to reduce your customer service queries by 85%. Set-up with no code under 4 minutes. Algomo learns from your data and integrates with major tools.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "low-code-no-code",
        name: "Low-code/no-code",
        name_locales: {
          de: "Low-Code/No-Code",
          en: "Low-code/no-code",
          es: "Low-code/No-code",
          fr: "Low-code/No-code",
          ja: "Low-code/No-code",
          ko: "로우코드/노코드",
          pt: "Low-code/no-code",
          tw: "低代码/无代码",
          vi: "Low-code/No-code",
          zh: "低代码/无代码",
        },
        tool_count: 228,
      },
      {
        handle: "customer-support",
        name: "Customer support",
        name_locales: {
          de: "Kundensupport",
          en: "Customer support",
          es: "Soporte al cliente",
          fr: "Support client",
          ja: "カスタマーサポート",
          ko: "고객 지원",
          pt: "Suporte ao cliente",
          tw: "客戶支援",
          vi: "Hỗ trợ khách hàng",
          zh: "客户支持",
        },
        tool_count: 260,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 12529,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 2337,
      growth_rate: 0.2293,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "yabble",
    name: "Yabble",
    website: "https://www.yabble.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454158242563362.jpg",
    description:
      "Yabble creates instant insights so you can take instant action. A suite of tools that create, count, summarize and chat with your data. Secure, automated AI solutions for every stage of research – Yabble is the leading AI solution for insights.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "research",
        name: "Research",
        name_locales: {
          de: "Forschung",
          en: "Research",
          es: "Investigación",
          fr: "Recherche",
          ja: "研究",
          ko: "연구",
          pt: "Pesquisa",
          tw: "研究",
          vi: "Nghiên cứu",
          zh: "研究",
        },
        tool_count: 161,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 38358,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: -5046,
      growth_rate: -0.1163,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "product-wingman",
    name: "Product Wingman",
    website:
      "https://chrome.google.com/webstore/detail/product-wingman/kgggmpenidfaelpnddcncjgbkcbikhmc",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454159875906670.jpg",
    description:
      "Product Wingman is an AI assistant for product managers helping them across entire product lifecycle. Do you want to consult your idea with AI product mastermind? Do you want to write user stories? Do you need go-to-market strategy? It's all there and more.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Browser Extension",
            handle: "browser-extension",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 256460079,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.2194574601803874,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.8377551073278602,
        },
        {
          title: "Search",
          value: 0.07984549844417992,
        },
        {
          title: "Referrals",
          value: 0.06527295668248258,
        },
      ],
      growth: 9323449,
      growth_rate: 0.0377,
      monthly_visits_mail: 157000,
      monthly_visits_direct: 214850741,
      monthly_visits_search: 20477183,
      monthly_visits_social: 3080286,
      monthly_visits_referrals: 16739908,
      monthly_visits_paid_referrals: 1154962,
      region_monthly_visits: null,
    },
  },
  {
    handle: "deepen",
    name: "Deepen",
    website: "https://thedeepen.app",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169416707583210233.jpg",
    description:
      "Your personal pocket therapist. Available for you 24/7, Deepen remembers and evolves with you over time; understanding your unique story. Need to get something off your chest? Want to explore your thoughts or your past? With Deepen, you can chat about anything",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "healthcare",
        name: "Healthcare",
        name_locales: {
          de: "Gesundheitsversorgung",
          en: "Healthcare",
          es: "Atención médica",
          fr: "Soins de santé",
          ja: "ヘルスケア",
          ko: "의료",
          pt: "Cuidados de saúde",
          tw: "醫療保健",
          vi: "Chăm sóc sức khỏe",
          zh: "医疗保健",
        },
        tool_count: 145,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 5256,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 5256,
      growth_rate: 0,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "leadsourcing",
    name: "Leadsourcing",
    website: "https://leadsourcing.co",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169416706650269139.jpg",
    description:
      "With one click, our tool can analyze each of the profile content and create personalized and relevant LinkedIn intro messages to your outreach campaign. Link: https://chrome.google.com/webstore/detail/leadsourcing-chatgpt-for/ogaoafnkmioibffoejjhojlgdbnbhbkn",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
      {
        handle: "sales",
        name: "Sales",
        name_locales: {
          de: "Verkauf",
          en: "Sales",
          es: "Venta",
          fr: "Vente",
          ja: "セールス",
          ko: "판매",
          pt: "Vendas",
          tw: "銷售",
          vi: "Bán hàng",
          zh: "销售",
        },
        tool_count: 158,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 2010,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 1762,
      growth_rate: 7.1048,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "kazava",
    name: "Kazava",
    website: "https://kazava.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169416702039339616.jpg",
    description:
      "Kazava offers an exceptional opportunity to experience the next generation of AI-powered technology, opening up new possibilities for engaging and immersive interactions.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "life-assistant",
        name: "Life assistant",
        name_locales: {
          de: "Lebensassistent",
          en: "Life assistant",
          es: "Asistente de vida",
          fr: "Assistant de vie",
          ja: "ライフアシスタント",
          ko: "라이프 어시스턴트",
          pt: "Assistente de vida",
          tw: "生活助理",
          vi: "Trợ lý cuộc sống",
          zh: "生活助手",
        },
        tool_count: 121,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "vplate-video-ads-chat-gpt-plugin",
    name: "VPLATE Video Ads - Chat GPT Plugin",
    website: "https://vplate.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169416700889750567.jpg",
    description:
      "VPLATE Video Ads is an automated short-form video Ads creation plugin. It allows users to simply chat, and the AI automatically generate the video Ads. Just input your product information in Chat GPT and experience the creation of an amazing short-form ad.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "video-generator",
        name: "Video generator",
        name_locales: {
          de: "Video-Generator",
          en: "Video generator",
          es: "Generador de videos",
          fr: "Générateur de vidéo",
          ja: "ビデオジェネレーター",
          ko: "비디오 생성기",
          pt: "Gerador de vídeos",
          tw: "影片產生器",
          vi: "Trình tạo video",
          zh: "视频生成器",
        },
        tool_count: 107,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 1570,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 78,
      growth_rate: 0.0523,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "hostomo",
    name: "Hostomo",
    website: "https://hostomo.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169416700357030927.jpg",
    description:
      "Hostomo is an AI-powered website builder that allows you to create unlimited websites in under a minute.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "dilgpt",
    name: "DilGPT",
    website: "https://dilgpt.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169416699067160314.jpg",
    description:
      "DilGPT: Your language learning BFF, utilizing best AI technologies and practices at language learning to boost fluency and courage to try. Practice, get away from your shyness, make mistakes and start learning!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
      {
        handle: "language-learning",
        name: "Language learning",
        name_locales: {
          de: "Sprachenlernen",
          en: "Language learning",
          es: "Aprendizaje de idiomas",
          fr: "Apprentissage des langues",
          ja: "言語学習",
          ko: "언어 학습",
          pt: "Aprendizagem de idiomas",
          tw: "語言學習",
          vi: "Học ngôn ngữ",
          zh: "语言学习",
        },
        tool_count: 235,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "promptblocks",
    name: "Promptblocks",
    website: "https://promptblocks.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169416695165198637.jpg",
    description:
      "Social prompt engineering platform for AI app developers. Save, reuse, and refine your prompts, share with the community, and deploy your prompts effortlessly.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "promtify",
    name: "Promtify",
    website: "https://www.promtify.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169409379791351409.jpg",
    description:
      "With Promtify, you can turn complex prompts into easy-to-use templates, use them for work and entertainment, and even share them with the community.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "resources",
        name: "Resources",
        name_locales: {
          de: "Ressourcen",
          en: "Resources",
          es: "Recursos",
          fr: "Ressources",
          ja: "リソース",
          ko: "자원",
          pt: "Recursos",
          tw: "資源",
          vi: "Tài nguyên",
          zh: "资源",
        },
        tool_count: 67,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "taste-bud",
    name: "Taste Bud",
    website: "https://taste-bud.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169409391366158087.jpg",
    description:
      "Elevate your culinary journey with Taste Bud, your AI-powered sous chef. Create delicious recipes using what's in your pantry, tailored to your preferences, equipment, and schedule. Unleash your inner chef and savor every bite with Taste Bud.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
];
