export const All = [
  {
    handle: "durable",
    name: "Durable",
    website:
      "https://durable.co/?utm_medium=Website%20Listing&utm_campaign=Toolify&utm_source=Website&utm_content=&utm_term=Toolify",
    image:
      "https://cdn-images.toolify.ai/image/e6622ca65df37b8e53a309652f098e22.jpeg",
    description:
      "Get your business online in 30 seconds. The AI-powered platform for solo business owners. Generate a website, automate your marketing, and manage your finances.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "low-code-no-code",
        name: "Low-code/no-code",
        name_locales: {
          de: "Low-Code/No-Code",
          en: "Low-code/no-code",
          es: "Low-code/No-code",
          fr: "Low-code/No-code",
          ja: "Low-code/No-code",
          ko: "로우코드/노코드",
          pt: "Low-code/no-code",
          tw: "低代码/无代码",
          vi: "Low-code/No-code",
          zh: "低代码/无代码",
        },
        tool_count: 228,
      },
      {
        handle: "finance",
        name: "Finance",
        name_locales: {
          de: "Finanzen",
          en: "Finance",
          es: "Finanzas",
          fr: "Finance",
          ja: "財務",
          ko: "금융",
          pt: "Finanças",
          tw: "財務",
          vi: "Tài chính",
          zh: "金融",
        },
        tool_count: 158,
      },
      {
        handle: "startup-tools",
        name: "Startup tools",
        name_locales: {
          de: "Startup-Tools",
          en: "Startup tools",
          es: "Herramientas para startups",
          fr: "Outils de démarrage",
          ja: "スタートアップツール",
          ko: "스타트업 도구",
          pt: "Ferramentas para startups",
          tw: "啟動工具",
          vi: "Công cụ khởi nghiệp",
          zh: "初创企业工具",
        },
        tool_count: 188,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
      {
        handle: "pricing",
        name: "Pricing",
        options: [
          {
            name: "Free Trial",
            handle: "free-trial",
          },
          {
            name: "Paid",
            handle: "paid",
          },
          {
            name: "Free",
            handle: "free",
          },
        ],
      },
    ],
    prices: [
      {
        cycle: "",
        price: "Free for 90 days",
        title: "Free Trial",
      },
      {
        cycle: "",
        price: "$15/mo",
        title: "Starter",
      },
      {
        cycle: "",
        price: "$25/mo",
        title: "Business",
      },
    ],
    month_visited_count: 2001279,
    collected_count: 16,
    user_collected: 0,
    traffic: {
      top_region: "IN",
      top_region_value: 0.14918803774435277,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.5073851771175729,
        },
        {
          title: "Search",
          value: 0.3862858780539709,
        },
        {
          title: "Social",
          value: 0.05781129695394565,
        },
      ],
      growth: -396365,
      growth_rate: -0.1653,
      monthly_visits_mail: 19917,
      monthly_visits_direct: 1015419,
      monthly_visits_search: 773066,
      monthly_visits_social: 115697,
      monthly_visits_referrals: 76667,
      monthly_visits_paid_referrals: 514,
      region_monthly_visits: null,
    },
  },
  {
    handle: "flot-ai",
    name: "Flot.ai",
    website: "https://flot.ai/?utm_source=toolify",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169357118260794822.jpg",
    description:
      "Flot.ai: AI Copilot for All Apps and Websites\n\nUse ChatGPT anywhere you type or select, On All Apps and Websites.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "document-assistant",
        name: "Document Assistant",
        name_locales: {
          de: "Dokumentenassistent",
          en: "Document Assistant",
          es: "Asistente de documentos",
          fr: "Assistant de document",
          ja: "文書アシスタント",
          ko: "문서 도우미",
          pt: "Assistente de documentos",
          tw: "文件助手",
          vi: "Trợ lý tài liệu",
          zh: "文档助手",
        },
        tool_count: 187,
      },
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "general-writing",
        name: "General writing",
        name_locales: {
          de: "Allgemeine Schreibarbeit",
          en: "General writing",
          es: "Escritura general",
          fr: "Écriture générale",
          ja: "一般的な文章",
          ko: "일반적인 작성",
          pt: "Escrita geral",
          tw: "一般寫作",
          vi: "Viết chung",
          zh: "常规写作",
        },
        tool_count: 343,
      },
      {
        handle: "paraphraser",
        name: "Paraphraser",
        name_locales: {
          de: "Paraphrasierungsprogramm",
          en: "Paraphraser",
          es: "Paráfrasis",
          fr: "Paraphraseur",
          ja: "パラフレーザー",
          ko: "바꾸기 도구",
          pt: "Paráfrase",
          tw: "改寫工具",
          vi: "Công cụ thay đổi văn bản",
          zh: "改写工具",
        },
        tool_count: 38,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "seo",
        name: "SEO",
        name_locales: {
          de: "SEO",
          en: "SEO",
          es: "SEO",
          fr: "SEO",
          ja: "検索エンジン最適化",
          ko: "검색 엔진 최적화",
          pt: "SEO",
          tw: "搜尋引擎最佳化",
          vi: "tối ưu hóa công cụ tìm kiếm",
          zh: "搜索引擎优化",
        },
        tool_count: 264,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "story-teller",
        name: "Story teller",
        name_locales: {
          de: "Geschichtenerzähler",
          en: "Story teller",
          es: "Cuentacuentos",
          fr: "Conteur d'histoires",
          ja: "語り部",
          ko: "이야기꾼",
          pt: "Contador de histórias",
          tw: "故事講述者",
          vi: "Người kể chuyện",
          zh: "讲故事人",
        },
        tool_count: 126,
      },
      {
        handle: "summarizer",
        name: "Summarizer",
        name_locales: {
          de: "Summarizer",
          en: "Summarizer",
          es: "Generador de resúmenes",
          fr: "Résumeur",
          ja: "要約作成ツール",
          ko: "요약 생성기",
          pt: "Resumidor",
          tw: "摘要產生器",
          vi: "Trình tóm tắt",
          zh: "摘要生成器",
        },
        tool_count: 196,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
      {
        handle: "pricing",
        name: "Pricing",
        options: [
          {
            name: "Paid",
            handle: "paid",
          },
          {
            name: "Free",
            handle: "free",
          },
        ],
      },
    ],
    prices: [],
    month_visited_count: 0,
    collected_count: 7,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "jasper",
    name: "Jasper",
    website: "https://jasper.ai?utm_source=partner&fpr=toolify28",
    image:
      "https://cdn-images.toolify.ai/image/a6b84578e2e1b892f4c99f51fa1b3d6e.jpeg",
    description:
      "Create content 10x faster with artificial intelligence. Jasper is the highest quality AI copywriting tool with over 3,000 5-star reviews. Best for writing blog posts, social media content, and marketing copy.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
      {
        handle: "pricing",
        name: "Pricing",
        options: [
          {
            name: "Paid",
            handle: "paid",
          },
        ],
      },
    ],
    prices: [
      {
        cycle: "",
        price: "$49 /mo",
        title: "Creator",
      },
      {
        cycle: "",
        price: "$125 /mo",
        title: "Teams",
      },
      {
        cycle: "",
        price: "Custom Pricing",
        title: "Business",
      },
    ],
    month_visited_count: 4754170,
    collected_count: 28,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.32655085420373947,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.6178732456048731,
        },
        {
          title: "Search",
          value: 0.2924263973646154,
        },
        {
          title: "Referrals",
          value: 0.0454580690152988,
        },
      ],
      growth: 601583,
      growth_rate: 0.1449,
      monthly_visits_mail: 78307,
      monthly_visits_direct: 2937474,
      monthly_visits_search: 1390245,
      monthly_visits_social: 128523,
      monthly_visits_referrals: 216115,
      monthly_visits_paid_referrals: 3506,
      region_monthly_visits: null,
    },
  },
  {
    handle: "fliki",
    name: "Fliki",
    website: "https://fliki.ai/?via=toolify",
    image:
      "https://cdn-images.toolify.ai/image/d7f56d67cde8ac32c1602b91aa8ae42e.jpeg",
    description:
      "Create videos from scripts or blog posts using realistic voices in 2 minutes!\nTransform blog articles into videos. Lifelike Text to Speech Voices. Rich stock media library.\nTrusted by 30k+ content creators from companies like Google, Meta, Bytedance and Upwork.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "text-to-speech",
        name: "Text to speech",
        name_locales: {
          de: "Text-zu-Sprache",
          en: "Text to speech",
          es: "Texto a voz",
          fr: "Texte à parole",
          ja: "テキスト読み上げ",
          ko: "문장 읽어주기",
          pt: "Texto para fala",
          tw: "文本轉語音",
          vi: "Văn bản thành giọng nói",
          zh: "文本转语音",
        },
        tool_count: 181,
      },
      {
        handle: "video-generator",
        name: "Video generator",
        name_locales: {
          de: "Video-Generator",
          en: "Video generator",
          es: "Generador de videos",
          fr: "Générateur de vidéo",
          ja: "ビデオジェネレーター",
          ko: "비디오 생성기",
          pt: "Gerador de vídeos",
          tw: "影片產生器",
          vi: "Trình tạo video",
          zh: "视频生成器",
        },
        tool_count: 107,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
      {
        handle: "pricing",
        name: "Pricing",
        options: [
          {
            name: "Paid",
            handle: "paid",
          },
          {
            name: "Free",
            handle: "free",
          },
        ],
      },
    ],
    prices: [
      {
        cycle:
          "📝 5 minutes of audio and video content per month  🎥 HD - 720p low-res videos  🔗 Convert Blog articles, PPT and Tweets  🇺🇸 300 (limited) voices, 75+ languages & 100+ dialects  ✐ Contains Fliki Watermark",
        price: "Free",
        title: "Free",
      },
      {
        cycle:
          "📝 120 minutes of audio content per month  🇺🇸 900+ voices, 75+ languages & 100+ dialects  🌎 Translate audio to 75+ languages  🏁 Audios of length upto 15 mins  © Commercial rights",
        price: "$8 per month",
        title: "Basic",
      },
      {
        cycle:
          "📝 180 minutes of audio / video content per month  🎥 Full HD - 1080p videos  🏁 Videos of length upto 15 mins  🌠 Millions of premium images, video clips and music assets  ✂︎ No Watermark",
        price: "$28 per month",
        title: "Standard",
      },
      {
        cycle:
          "📝 600 minutes of audio / video content per month  🏁 Videos of length upto 30 mins  🎙️ Voice Cloning  🗣️ Ultra realistic voices  🔌 API access  ‍👩‍💼 Dedicated account manager",
        price: "$88 per month",
        title: "Premium",
      },
    ],
    month_visited_count: 2604398,
    collected_count: 60,
    user_collected: 0,
    traffic: {
      top_region: "BR",
      top_region_value: 0.16129043114479194,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.532173062078214,
        },
        {
          title: "Search",
          value: 0.3015045708832396,
        },
        {
          title: "Social",
          value: 0.09550732762054268,
        },
      ],
      growth: -795132,
      growth_rate: -0.2339,
      monthly_visits_mail: 14567,
      monthly_visits_direct: 1385990,
      monthly_visits_search: 785238,
      monthly_visits_social: 248739,
      monthly_visits_referrals: 167756,
      monthly_visits_paid_referrals: 2107,
      region_monthly_visits: null,
    },
  },
  {
    handle: "chatpdf",
    name: "Chatpdf",
    website: "https://www.chatpdf.com/?via=toolify",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168197409571939545.jpg",
    description:
      "ChatPDF is a tool that allows users to interact with PDF documents using natural language processing and artificial intelligence. It can extract text from PDFs and feed it to GPT for analysis2. The tool can be used to extract information from large PDF files such as manuals, essays, legal contracts, books, or research papers3.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "resources",
        name: "Resources",
        name_locales: {
          de: "Ressourcen",
          en: "Resources",
          es: "Recursos",
          fr: "Ressources",
          ja: "リソース",
          ko: "자원",
          pt: "Recursos",
          tw: "資源",
          vi: "Tài nguyên",
          zh: "资源",
        },
        tool_count: 67,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "pricing",
        name: "Pricing",
        options: [
          {
            name: "Paid",
            handle: "paid",
          },
          {
            name: "Free",
            handle: "free",
          },
        ],
      },
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: [
      {
        cycle: "120 pages/PDF 10 MB/PDF 3 PDFs/day 50 questions/day",
        price: "$0/mo",
        title: "Free",
      },
      {
        cycle: "2,000 pages/PDF 32 MB/PDF 50 PDFs/day 1000 questions/day",
        price: "$5/mo",
        title: "Plus",
      },
    ],
    month_visited_count: 6029365,
    collected_count: 68,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.18028059737304733,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.6787121851834852,
        },
        {
          title: "Search",
          value: 0.25771062332559524,
        },
        {
          title: "Referrals",
          value: 0.03774841208427635,
        },
      ],
      growth: -1758543,
      growth_rate: -0.2258,
      monthly_visits_mail: 14524,
      monthly_visits_direct: 4092203,
      monthly_visits_search: 1553831,
      monthly_visits_social: 139399,
      monthly_visits_referrals: 227599,
      monthly_visits_paid_referrals: 1808,
      region_monthly_visits: null,
    },
  },
  {
    handle: "hix-ai",
    name: "Hix AI",
    website: "https://hix.ai/?ref=yzqxndr6",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169054819035381052.jpg",
    description:
      "Generate high-quality copies for ads, emails, blogs, and more in seconds with HIX.AI, the most powerful, all-in-one AI writing copilot on the market.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "general-writing",
        name: "General writing",
        name_locales: {
          de: "Allgemeine Schreibarbeit",
          en: "General writing",
          es: "Escritura general",
          fr: "Écriture générale",
          ja: "一般的な文章",
          ko: "일반적인 작성",
          pt: "Escrita geral",
          tw: "一般寫作",
          vi: "Viết chung",
          zh: "常规写作",
        },
        tool_count: 343,
      },
      {
        handle: "paraphraser",
        name: "Paraphraser",
        name_locales: {
          de: "Paraphrasierungsprogramm",
          en: "Paraphraser",
          es: "Paráfrasis",
          fr: "Paraphraseur",
          ja: "パラフレーザー",
          ko: "바꾸기 도구",
          pt: "Paráfrase",
          tw: "改寫工具",
          vi: "Công cụ thay đổi văn bản",
          zh: "改写工具",
        },
        tool_count: 38,
      },
      {
        handle: "seo",
        name: "SEO",
        name_locales: {
          de: "SEO",
          en: "SEO",
          es: "SEO",
          fr: "SEO",
          ja: "検索エンジン最適化",
          ko: "검색 엔진 최적화",
          pt: "SEO",
          tw: "搜尋引擎最佳化",
          vi: "tối ưu hóa công cụ tìm kiếm",
          zh: "搜索引擎优化",
        },
        tool_count: 264,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "summarizer",
        name: "Summarizer",
        name_locales: {
          de: "Summarizer",
          en: "Summarizer",
          es: "Generador de resúmenes",
          fr: "Résumeur",
          ja: "要約作成ツール",
          ko: "요약 생성기",
          pt: "Resumidor",
          tw: "摘要產生器",
          vi: "Trình tóm tắt",
          zh: "摘要生成器",
        },
        tool_count: 196,
      },
      {
        handle: "e-commerce",
        name: "E-commerce",
        name_locales: {
          de: "E-Commerce",
          en: "E-commerce",
          es: "Comercio electrónico",
          fr: "Commerce électronique",
          ja: "Eコマース",
          ko: "전자상거래",
          pt: "Comércio eletrônico",
          tw: "電子商務",
          vi: "Thương mại điện tử",
          zh: "电子商务",
        },
        tool_count: 215,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
      {
        handle: "pricing",
        name: "Pricing",
        options: [
          {
            name: "Paid",
            handle: "paid",
          },
          {
            name: "Free",
            handle: "free",
          },
        ],
      },
    ],
    prices: [],
    month_visited_count: 19250,
    collected_count: 32,
    user_collected: 0,
    traffic: {
      top_region: "HK",
      top_region_value: 0.3944464310670012,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.6501487715922396,
        },
        {
          title: "Search",
          value: 0.19105278875881593,
        },
        {
          title: "Mail",
          value: 0.0842600773322923,
        },
      ],
      growth: -18593,
      growth_rate: -0.4913,
      monthly_visits_mail: 1622,
      monthly_visits_direct: 12515,
      monthly_visits_search: 3678,
      monthly_visits_social: 0,
      monthly_visits_referrals: 1435,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "swifto",
    name: "Swifto",
    website: "https://swifto.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454297147493058.jpg",
    description:
      "Let your website optimize itself on AutoPilot Get more sales and signups with Generative AI A/B testing No need for a designer, frontend developer, or UX researcher",
    description_locales: null,
    review: null,
    categories: [],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "m00d-ritual",
    name: "M00D Ritual",
    website: "https://m00d.tech",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454285311466173.jpg",
    description:
      "M👀D Ritual is the easiest way to run self sovereign AI image generation, supporting Stable Diffusion 1.5 and XL. Featuring a unique Timeline interface to collaborate entirely fluid with the AI, think ChatGPT for image gen.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "art",
        name: "Art",
        name_locales: {
          de: "Kunst",
          en: "Art",
          es: "Arte",
          fr: "Art",
          ja: "芸術",
          ko: "예술",
          pt: "Arte",
          tw: "藝術",
          vi: "Nghệ thuật",
          zh: "艺术",
        },
        tool_count: 398,
      },
      {
        handle: "image-generator",
        name: "Image generator",
        name_locales: {
          de: "Bildgenerator",
          en: "Image generator",
          es: "Generador de imágenes",
          fr: "Générateur d'images",
          ja: "画像生成器",
          ko: "이미지 생성기",
          pt: "Gerador de imagens",
          tw: "圖像生成器",
          vi: "Trình tạo hình ảnh",
          zh: "图像生成器",
        },
        tool_count: 298,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "designai",
    name: "DesignAi",
    website: "https://www.designai.us",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454285990273275.jpg",
    description:
      "Unveiling a game-changer in the world of interior design! My revolutionary web application takes your interior design and design boards to the next level, seamlessly integrating Artificial Intelligence to visualize your dream spaces.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "design-assistant",
        name: "Design assistant",
        name_locales: {
          de: "Design-Assistent",
          en: "Design assistant",
          es: "Asistente de diseño",
          fr: "Assistant de conception",
          ja: "デザインアシスタント",
          ko: "디자인 어시스턴트",
          pt: "Assistente de design",
          tw: "設計助手",
          vi: "Trợ lý thiết kế",
          zh: "设计助手",
        },
        tool_count: 306,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "cerbrec-graphbook",
    name: "Cerbrec Graphbook",
    website: "https://www.cerbrec.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454286750681971.jpg",
    description:
      "Graphbook is a deep learning framework with a visual interface, transforming, cumbersome model development into a user-friendly experience. With Graphbook you can edit and debug deep learning models as a drag-and-drop data orchestrator for inside your models.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 515,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: -1405,
      growth_rate: -0.7318,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "ai-interior-room-planner",
    name: "AI Interior Room Planner",
    website: "https://aiinteriorplanner.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454286732704054.jpg",
    description:
      "Transform your living space with InteriorAI Room Planner, your AI-powered interior designer. Snap a photo of your room, and watch AI craft the perfect design. Chat with AI design expert for personalized advice, bringing your vision to life effortlessly.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "design-assistant",
        name: "Design assistant",
        name_locales: {
          de: "Design-Assistent",
          en: "Design assistant",
          es: "Asistente de diseño",
          fr: "Assistant de conception",
          ja: "デザインアシスタント",
          ko: "디자인 어시스턴트",
          pt: "Assistente de design",
          tw: "設計助手",
          vi: "Trợ lý thiết kế",
          zh: "设计助手",
        },
        tool_count: 306,
      },
      {
        handle: "real-estate",
        name: "Real estate",
        name_locales: {
          de: "Immobilien",
          en: "Real estate",
          es: "Bienes raíces",
          fr: "Immobilier",
          ja: "不動産",
          ko: "부동산",
          pt: "Imobiliário",
          tw: "房地產",
          vi: "Bất động sản",
          zh: "房地产",
        },
        tool_count: 66,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "siesta",
    name: "Siesta",
    website: "https://siestaguides.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454287535920842.jpg",
    description:
      "Tailored marketing plans that help even the smallest teams achieve big dreams. Complete a 15-minute survey, receive the guide in 48 hours and transform your marketing into a results-driven endeavour.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "chatfuro",
    name: "Chatfuro",
    website: "https://chatfuro.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454287638775970.jpg",
    description:
      "Get your own ChatGPT bots in minutes. Chatfuro helps streamline your chatbots for multiple purposes to ask questions and find information, or embed as a widget on your website to assist your users.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
      {
        handle: "customer-support",
        name: "Customer support",
        name_locales: {
          de: "Kundensupport",
          en: "Customer support",
          es: "Soporte al cliente",
          fr: "Support client",
          ja: "カスタマーサポート",
          ko: "고객 지원",
          pt: "Suporte ao cliente",
          tw: "客戶支援",
          vi: "Hỗ trợ khách hàng",
          zh: "客户支持",
        },
        tool_count: 260,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "aurum-kuberx",
    name: "Aurum KuberX",
    website: "https://www.aurumkuberx.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454288570039957.jpg",
    description:
      "AI-driven Loans Platform that provides accurate loans recommendations and offers the best finance options.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "finance",
        name: "Finance",
        name_locales: {
          de: "Finanzen",
          en: "Finance",
          es: "Finanzas",
          fr: "Finance",
          ja: "財務",
          ko: "금융",
          pt: "Finanças",
          tw: "財務",
          vi: "Tài chính",
          zh: "金融",
        },
        tool_count: 158,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "ai-persona-chat",
    name: "AI Persona Chat",
    website:
      "https://apps.apple.com/us/app/ai-personas-characters/id6456891746",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454288793452491.jpg",
    description:
      "Converse with legendary figures, explore diverse topics, and discover unique personas tailored for every mood. Powered by cutting-edge AI for lifelike conversations. Fresh, exciting, and ever-evolving. Join the chat revolution!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "experiments",
        name: "Experiments",
        name_locales: {
          de: "Experimente",
          en: "Experiments",
          es: "Experimentos",
          fr: "Expériences",
          ja: "実験",
          ko: "실험",
          pt: "Experimentos",
          tw: "實驗",
          vi: "Thí nghiệm",
          zh: "实验",
        },
        tool_count: 49,
      },
      {
        handle: "fun-tools",
        name: "Fun tools",
        name_locales: {
          de: "Spaßwerkzeuge",
          en: "Fun tools",
          es: "Herramientas divertidas",
          fr: "Outils amusants",
          ja: "楽しいツール",
          ko: "재미있는 도구",
          pt: "Ferramentas divertidas",
          tw: "有趣工具",
          vi: "Công cụ vui nhộn",
          zh: "趣味工具",
        },
        tool_count: 197,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
      {
        handle: "language-learning",
        name: "Language learning",
        name_locales: {
          de: "Sprachenlernen",
          en: "Language learning",
          es: "Aprendizaje de idiomas",
          fr: "Apprentissage des langues",
          ja: "言語学習",
          ko: "언어 학습",
          pt: "Aprendizagem de idiomas",
          tw: "語言學習",
          vi: "Học ngôn ngữ",
          zh: "语言学习",
        },
        tool_count: 235,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "App",
            handle: "app",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 118449982,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.24253346927315403,
      top_traffic_sources: [
        {
          title: "Search",
          value: 0.34298605945565247,
        },
        {
          title: "Referrals",
          value: 0.31164588745370364,
        },
        {
          title: "Direct",
          value: 0.23273471611265417,
        },
      ],
      growth: -2523202,
      growth_rate: -0.0209,
      monthly_visits_mail: 1295492,
      monthly_visits_direct: 27567423,
      monthly_visits_search: 40626693,
      monthly_visits_social: 4189658,
      monthly_visits_referrals: 36914450,
      monthly_visits_paid_referrals: 7856266,
      region_monthly_visits: null,
    },
  },
  {
    handle: "soft-skills-cloud",
    name: "Soft Skills Cloud",
    website: "https://soft-skills.cloud",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454289418159280.jpg",
    description:
      "We strive to improve your business writing skills, with the right tools. Drop your text, and receive detailed review of it with nice editing UI.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "chatfolio",
    name: "Chatfolio",
    website: "https://chatfolio.org",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454289566211345.jpg",
    description:
      "Introducing Chatfolio: a chatbot for your portfolio website that can answer any questions about your resume, skills, experience..etc. Upload your resume, add it to your site, and watch how it can instantly enhance your site's experience. Try now for free!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "credit-chip",
    name: "Credit Chip",
    website: "https://mobilecredits.app",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454291259399336.jpg",
    description:
      "Credit chips are designed to accept instant person-2-person payments using NFC, URL, QR code, Wearables, MetaMask, Ledger, Trezor, Visa, Mastercard, American Express, Discover, Apple Pay, Google Pay and many more for borderless and instantaneous payments.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "e-commerce",
        name: "E-commerce",
        name_locales: {
          de: "E-Commerce",
          en: "E-commerce",
          es: "Comercio electrónico",
          fr: "Commerce électronique",
          ja: "Eコマース",
          ko: "전자상거래",
          pt: "Comércio eletrônico",
          tw: "電子商務",
          vi: "Thương mại điện tử",
          zh: "电子商务",
        },
        tool_count: 215,
      },
      {
        handle: "finance",
        name: "Finance",
        name_locales: {
          de: "Finanzen",
          en: "Finance",
          es: "Finanzas",
          fr: "Finance",
          ja: "財務",
          ko: "금융",
          pt: "Finanças",
          tw: "財務",
          vi: "Tài chính",
          zh: "金融",
        },
        tool_count: 158,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "ai-score-my-site",
    name: "AI Score My Site",
    website: "https://aiscoremy.site",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454291286895315.jpg",
    description:
      "Find out if your website can be discovered and ranked by AI powered search engines in the future. AI Score My Site will index your site, formulate questions and see how your website answers, then make suggestions on how you can improve.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "seo",
        name: "SEO",
        name_locales: {
          de: "SEO",
          en: "SEO",
          es: "SEO",
          fr: "SEO",
          ja: "検索エンジン最適化",
          ko: "검색 엔진 최적화",
          pt: "SEO",
          tw: "搜尋引擎最佳化",
          vi: "tối ưu hóa công cụ tìm kiếm",
          zh: "搜索引擎优化",
        },
        tool_count: 264,
      },
      {
        handle: "search-engine",
        name: "Search engine",
        name_locales: {
          de: "Suchmaschine",
          en: "Search engine",
          es: "Motor de búsqueda",
          fr: "Moteur de recherche",
          ja: "検索エンジン",
          ko: "검색 엔진",
          pt: "Motor de busca",
          tw: "搜尋引擎",
          vi: "Máy tìm kiếm",
          zh: "搜索引擎",
        },
        tool_count: 172,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "footagentexam-com",
    name: "footagentexam.com",
    website: "https://www.footagentexam.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454296576858200.jpg",
    description:
      "FootAgentExam.com is your gateway to mastering the FIFA football agent exam with cutting-edge AI-powered learning, interactive quizzes, and time-saving features. Elevate your game in the world of football agents with our revolutionary platform. ⚽️🤖📚",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "education-assistant",
        name: "Education assistant",
        name_locales: {
          de: "Bildungsassistent",
          en: "Education assistant",
          es: "Asistente de educación",
          fr: "Assistant d'éducation",
          ja: "教育アシスタント",
          ko: "교육 조수",
          pt: "Assistente de educação",
          tw: "教育助理",
          vi: "Trợ lý giáo dục",
          zh: "教育助理",
        },
        tool_count: 337,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "infichat",
    name: "Infichat",
    website: "https://infichat.co",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454296365650272.jpg",
    description:
      "A better way to give your customers the support they need without spending a fortune. Increase revenue, keep customers happy and reduce churn!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "customer-support",
        name: "Customer support",
        name_locales: {
          de: "Kundensupport",
          en: "Customer support",
          es: "Soporte al cliente",
          fr: "Support client",
          ja: "カスタマーサポート",
          ko: "고객 지원",
          pt: "Suporte ao cliente",
          tw: "客戶支援",
          vi: "Hỗ trợ khách hàng",
          zh: "客户支持",
        },
        tool_count: 260,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 1653,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: -2232,
      growth_rate: -0.5745,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "arch",
    name: "Arch",
    website: "https://arch.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454295729047213.jpg",
    description:
      "Arch harnesses AI to condense your emails into succinct summaries, suggest responses, and draft emails for you according to your instructions.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "prevessai-app",
    name: "PrevessAI App",
    website: "https://www.prevess.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454295439731742.jpg",
    description:
      "Your personal nutritionist, always online. PrevessAI is there when you don't know what to eat to meet your calorie needs; when you've sustained an injury & need recovery. It's the PrevessAI app for enhancing athletic performance and taking care of your health.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "personalized-videos",
        name: "Personalized videos",
        name_locales: {
          de: "Personalisierte Videos",
          en: "Personalized videos",
          es: "Videos personalizados",
          fr: "Vidéos personnalisées",
          ja: "パーソナライズ動画",
          ko: "맞춤형 비디오",
          pt: "Vídeos personalizados",
          tw: "個人化影片",
          vi: "Video cá nhân hóa",
          zh: "个性化视频",
        },
        tool_count: 129,
      },
      {
        handle: "healthcare",
        name: "Healthcare",
        name_locales: {
          de: "Gesundheitsversorgung",
          en: "Healthcare",
          es: "Atención médica",
          fr: "Soins de santé",
          ja: "ヘルスケア",
          ko: "의료",
          pt: "Cuidados de saúde",
          tw: "醫療保健",
          vi: "Chăm sóc sức khỏe",
          zh: "医疗保健",
        },
        tool_count: 145,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 23205,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 3454,
      growth_rate: 0.1749,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "interviewspark",
    name: "InterviewSpark",
    website: "https://interviewspark.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454294755321639.jpg",
    description:
      "InterviewSpark is a SaaS e-learning platform and Interview strategist focusing on AI-driven Interview Prep. It conducts realistic mock interviews from a collection of over 1,000 curated questions and offers actionable, data-driven feedback all in real time.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "education-assistant",
        name: "Education assistant",
        name_locales: {
          de: "Bildungsassistent",
          en: "Education assistant",
          es: "Asistente de educación",
          fr: "Assistant d'éducation",
          ja: "教育アシスタント",
          ko: "교육 조수",
          pt: "Assistente de educação",
          tw: "教育助理",
          vi: "Trợ lý giáo dục",
          zh: "教育助理",
        },
        tool_count: 337,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 216,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 216,
      growth_rate: 0,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "coinfeeds",
    name: "Coinfeeds",
    website: "https://www.coinfeeds.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454294669332374.jpg",
    description:
      "Coinfeeds transforms the complex world of cryptocurrency into simple, digestible insights for everyone. Powered by AI, our platform ensures efficient, high-quality analysis tailored for a broad audience.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "finance",
        name: "Finance",
        name_locales: {
          de: "Finanzen",
          en: "Finance",
          es: "Finanzas",
          fr: "Finance",
          ja: "財務",
          ko: "금융",
          pt: "Finanças",
          tw: "財務",
          vi: "Tài chính",
          zh: "金融",
        },
        tool_count: 158,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 5981,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 5161,
      growth_rate: 6.2939,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "essay-builder-ai",
    name: "Essay Builder AI",
    website: "https://essay-builder.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454293088569070.jpg",
    description:
      "📝 Make exceptional essays effortlessly with Essay-Builder.ai - the free AI-powered tool that helps you to generate top-notch essays in seconds. Choose your essay type, and number of words, and let Essay-Builder.ai do the rest!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "general-writing",
        name: "General writing",
        name_locales: {
          de: "Allgemeine Schreibarbeit",
          en: "General writing",
          es: "Escritura general",
          fr: "Écriture générale",
          ja: "一般的な文章",
          ko: "일반적인 작성",
          pt: "Escrita geral",
          tw: "一般寫作",
          vi: "Viết chung",
          zh: "常规写作",
        },
        tool_count: 343,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 72080,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: -1100,
      growth_rate: -0.015,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "docuspeed",
    name: "DocuSpeed",
    website: "https://docuspeed.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454293851683608.jpg",
    description:
      "Meet DocuSpeed: Your AI-powered reading companion for PDFs. Quickly extract key insights, ask content-specific questions, and bypass language barriers with full-text translations. Transform your reading experience and save precious time.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
      {
        handle: "document-assistant",
        name: "Document Assistant",
        name_locales: {
          de: "Dokumentenassistent",
          en: "Document Assistant",
          es: "Asistente de documentos",
          fr: "Assistant de document",
          ja: "文書アシスタント",
          ko: "문서 도우미",
          pt: "Assistente de documentos",
          tw: "文件助手",
          vi: "Trợ lý tài liệu",
          zh: "文档助手",
        },
        tool_count: 187,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "lyras-ai",
    name: "Lyras AI",
    website: "https://lyras.cloud",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454290333965661.jpg",
    description:
      "3x your leads or double staff productivity - conversational AI tools all in one space. Lyras is an AI powered enterprise partner, we help businesses better understand and utilise their traffic.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
      {
        handle: "customer-support",
        name: "Customer support",
        name_locales: {
          de: "Kundensupport",
          en: "Customer support",
          es: "Soporte al cliente",
          fr: "Support client",
          ja: "カスタマーサポート",
          ko: "고객 지원",
          pt: "Suporte ao cliente",
          tw: "客戶支援",
          vi: "Hỗ trợ khách hàng",
          zh: "客户支持",
        },
        tool_count: 260,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "iwish",
    name: "iWish",
    website: "https://www.iwish.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454292072047090.jpg",
    description:
      "Welcome to the future of seamless tech support. iWish AI is designed to automate tech support and thus transforming your customer experience.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "customer-support",
        name: "Customer support",
        name_locales: {
          de: "Kundensupport",
          en: "Customer support",
          es: "Soporte al cliente",
          fr: "Support client",
          ja: "カスタマーサポート",
          ko: "고객 지원",
          pt: "Suporte ao cliente",
          tw: "客戶支援",
          vi: "Hỗ trợ khách hàng",
          zh: "客户支持",
        },
        tool_count: 260,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 7405,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 6388,
      growth_rate: 6.2812,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "gen-expert",
    name: "Gen Expert",
    website: "https://genexpert.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454293895847019.jpg",
    description:
      "Supercharge your chatgpt experience with GenExpert. Unleash the power of customizable GPT models, captivating prompts, and documents with AI auto-completion. Effortlessly create top-notch content, save time, and enjoy ultimate privacy and security.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "general-writing",
        name: "General writing",
        name_locales: {
          de: "Allgemeine Schreibarbeit",
          en: "General writing",
          es: "Escritura general",
          fr: "Écriture générale",
          ja: "一般的な文章",
          ko: "일반적인 작성",
          pt: "Escrita geral",
          tw: "一般寫作",
          vi: "Viết chung",
          zh: "常规写作",
        },
        tool_count: 343,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "code-assistant",
        name: "Code assistant",
        name_locales: {
          de: "Code-Assistent",
          en: "Code assistant",
          es: "Asistente de código",
          fr: "Assistant de code",
          ja: "コードアシスタント",
          ko: "코드 어시스턴트",
          pt: "Assistente de código",
          tw: "代碼助手",
          vi: "Trợ lý mã",
          zh: "代码辅助工具",
        },
        tool_count: 165,
      },
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
      {
        handle: "document-assistant",
        name: "Document Assistant",
        name_locales: {
          de: "Dokumentenassistent",
          en: "Document Assistant",
          es: "Asistente de documentos",
          fr: "Assistant de document",
          ja: "文書アシスタント",
          ko: "문서 도우미",
          pt: "Assistente de documentos",
          tw: "文件助手",
          vi: "Trợ lý tài liệu",
          zh: "文档助手",
        },
        tool_count: 187,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
];
