export const EmailAssistant = [
  {
    handle: "flot-ai",
    name: "Flot.ai",
    website: "https://flot.ai/?utm_source=toolify",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169357118260794822.jpg",
    description:
      "Flot.ai: AI Copilot for All Apps and Websites\n\nUse ChatGPT anywhere you type or select, On All Apps and Websites.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "document-assistant",
        name: "Document Assistant",
        name_locales: {
          de: "Dokumentenassistent",
          en: "Document Assistant",
          es: "Asistente de documentos",
          fr: "Assistant de document",
          ja: "文書アシスタント",
          ko: "문서 도우미",
          pt: "Assistente de documentos",
          tw: "文件助手",
          vi: "Trợ lý tài liệu",
          zh: "文档助手",
        },
        tool_count: 187,
      },
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "general-writing",
        name: "General writing",
        name_locales: {
          de: "Allgemeine Schreibarbeit",
          en: "General writing",
          es: "Escritura general",
          fr: "Écriture générale",
          ja: "一般的な文章",
          ko: "일반적인 작성",
          pt: "Escrita geral",
          tw: "一般寫作",
          vi: "Viết chung",
          zh: "常规写作",
        },
        tool_count: 343,
      },
      {
        handle: "paraphraser",
        name: "Paraphraser",
        name_locales: {
          de: "Paraphrasierungsprogramm",
          en: "Paraphraser",
          es: "Paráfrasis",
          fr: "Paraphraseur",
          ja: "パラフレーザー",
          ko: "바꾸기 도구",
          pt: "Paráfrase",
          tw: "改寫工具",
          vi: "Công cụ thay đổi văn bản",
          zh: "改写工具",
        },
        tool_count: 38,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "seo",
        name: "SEO",
        name_locales: {
          de: "SEO",
          en: "SEO",
          es: "SEO",
          fr: "SEO",
          ja: "検索エンジン最適化",
          ko: "검색 엔진 최적화",
          pt: "SEO",
          tw: "搜尋引擎最佳化",
          vi: "tối ưu hóa công cụ tìm kiếm",
          zh: "搜索引擎优化",
        },
        tool_count: 264,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "story-teller",
        name: "Story teller",
        name_locales: {
          de: "Geschichtenerzähler",
          en: "Story teller",
          es: "Cuentacuentos",
          fr: "Conteur d'histoires",
          ja: "語り部",
          ko: "이야기꾼",
          pt: "Contador de histórias",
          tw: "故事講述者",
          vi: "Người kể chuyện",
          zh: "讲故事人",
        },
        tool_count: 126,
      },
      {
        handle: "summarizer",
        name: "Summarizer",
        name_locales: {
          de: "Summarizer",
          en: "Summarizer",
          es: "Generador de resúmenes",
          fr: "Résumeur",
          ja: "要約作成ツール",
          ko: "요약 생성기",
          pt: "Resumidor",
          tw: "摘要產生器",
          vi: "Trình tóm tắt",
          zh: "摘要生成器",
        },
        tool_count: 196,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
      {
        handle: "pricing",
        name: "Pricing",
        options: [
          {
            name: "Paid",
            handle: "paid",
          },
          {
            name: "Free",
            handle: "free",
          },
        ],
      },
    ],
    prices: [],
    month_visited_count: 0,
    collected_count: 7,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },

  {
    handle: "arch",
    name: "Arch",
    website: "https://arch.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454295729047213.jpg",
    description:
      "Arch harnesses AI to condense your emails into succinct summaries, suggest responses, and draft emails for you according to your instructions.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "cxassist",
    name: "CXassist",
    website: "https://www.cxassist.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454278586226032.jpg",
    description:
      "AI + Email = Productivity. CXassist can automatically manage your inbox for you, intelligently answering emails based on the training data you provide (PDF,txt,csv) giving you hours of productivity back, and providing limitless scale to your business.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "salesforge",
    name: "Salesforge",
    website: "https://salesforge.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169409392431355600.jpg",
    description:
      "Up to 89% open rate + 2x lift in reply rate vs using templates! 👀 Write unique emails using AI matching seller & buyer data while safeguarding your email deliverability via multi-inbox sequences, email warm-up, and email address validation.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "sales",
        name: "Sales",
        name_locales: {
          de: "Verkauf",
          en: "Sales",
          es: "Venta",
          fr: "Vente",
          ja: "セールス",
          ko: "판매",
          pt: "Vendas",
          tw: "銷售",
          vi: "Bán hàng",
          zh: "销售",
        },
        tool_count: 158,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 62010,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 37907,
      growth_rate: 1.5727,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "taskified",
    name: "Taskified",
    website: "https://taskified.co",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169384068941400447.jpg",
    description:
      "Designed as an extension, Taskified pops up in the corner of your screen, allowing you to read and send emails on the go. Furthermore, it uses AI to draft and summarize your emails, and automatically divides them into separate categories.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "emailwhiz-for-gmail",
    name: "EmailWhiz for Gmail™",
    website:
      "https://workspace.google.com/marketplace/app/emailwhiz_for_gmail/821716939565",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169357206267816524.jpg",
    description:
      "We are thrilled to announce EmailWhiz for Gmail's major upgrade, powered by Google's Vertex AI PaLM In addition to extracting contacts, new capabilities include: Summarize emails Get suggested replies Create tasks instantly Save key details to Google Sheets",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Workspace",
            handle: "workspace",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 54363162,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.3131164561758221,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.391120132245879,
        },
        {
          title: "Search",
          value: 0.3402217357831111,
        },
        {
          title: "Referrals",
          value: 0.21826634156508257,
        },
      ],
      growth: -3446924,
      growth_rate: -0.0596,
      monthly_visits_mail: 110892,
      monthly_visits_direct: 21262527,
      monthly_visits_search: 18495529,
      monthly_visits_social: 1432828,
      monthly_visits_referrals: 11865648,
      monthly_visits_paid_referrals: 1195737,
      region_monthly_visits: null,
    },
  },
  {
    handle: "textcraft-ai",
    name: "TextCraft AI",
    website:
      "https://chrome.google.com/webstore/detail/textcraft-ai/hifkcigdddheloapjflemfjojhfhopmh",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169357203331865819.jpg",
    description:
      "Chrome extension for Gmail, Outlook. 🚀✉️ Auto-generates emails, summarizes messages, and provides smart replies with AI. Supercharge your inbox! 🌟 Try it now! Easy to install and free to use.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Browser Extension",
            handle: "browser-extension",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 247136630,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.22191269346357223,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.8368373876173484,
        },
        {
          title: "Search",
          value: 0.08193425217161182,
        },
        {
          title: "Referrals",
          value: 0.06371080458066519,
        },
      ],
      growth: -2945035,
      growth_rate: -0.0118,
      monthly_visits_mail: 56903,
      monthly_visits_direct: 206813172,
      monthly_visits_search: 20248955,
      monthly_visits_social: 3399656,
      monthly_visits_referrals: 15745274,
      monthly_visits_paid_referrals: 872671,
      region_monthly_visits: null,
    },
  },
  {
    handle: "email-subject-line-generator",
    name: "Email Subject Line Generator",
    website: "https://subjectlinegenerator.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169348462219527537.jpg",
    description:
      "Struggling with email subject lines? Our AI-powered Subject Line Generator creates options tailored to your message. Choose your tone and even add emojis. If you use Gmail, it seamlessly integrates into your inbox for convenience.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 6806,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 3409,
      growth_rate: 1.0035,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "linkedly",
    name: "Linkedly",
    website: "https://linkedly.app",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169340876530882218.jpg",
    description:
      "Personalizes your outreach using ChatGPT - Scans profile to create a personalized message - Finds possible email addresses using Hunter.io - Ability to download generated connections to Excel",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "sales",
        name: "Sales",
        name_locales: {
          de: "Verkauf",
          en: "Sales",
          es: "Venta",
          fr: "Vente",
          ja: "セールス",
          ko: "판매",
          pt: "Vendas",
          tw: "銷售",
          vi: "Bán hàng",
          zh: "销售",
        },
        tool_count: 158,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "workgpt",
    name: "WorkGPT",
    website:
      "https://workspace.google.com/marketplace/app/workgpt_gpt_chatgpt_for_workspace/368806015202",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169330345223213377.jpg",
    description:
      "Best GPT AI assistant add-on for Google Docs, Slides, Gmail, Sheets powered by GPT-3.5, GPT-4 and LIama2. It will greatly help you edit and create content, write emails, process information, read and more, with 10x productivity and saving you many hours!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
      {
        handle: "document-assistant",
        name: "Document Assistant",
        name_locales: {
          de: "Dokumentenassistent",
          en: "Document Assistant",
          es: "Asistente de documentos",
          fr: "Assistant de document",
          ja: "文書アシスタント",
          ko: "문서 도우미",
          pt: "Assistente de documentos",
          tw: "文件助手",
          vi: "Trợ lý tài liệu",
          zh: "文档助手",
        },
        tool_count: 187,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Workspace",
            handle: "workspace",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 54363162,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.3131164561758221,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.391120132245879,
        },
        {
          title: "Search",
          value: 0.3402217357831111,
        },
        {
          title: "Referrals",
          value: 0.21826634156508257,
        },
      ],
      growth: -3446924,
      growth_rate: -0.0596,
      monthly_visits_mail: 110892,
      monthly_visits_direct: 21262527,
      monthly_visits_search: 18495529,
      monthly_visits_social: 1432828,
      monthly_visits_referrals: 11865648,
      monthly_visits_paid_referrals: 1195737,
      region_monthly_visits: null,
    },
  },
  {
    handle: "mailbuddy-chatgpt-ai-email-assistant",
    name: "MailBuddy - ChatGPT AI Email Assistant",
    website: "https://mailbuddy.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169295770365921399.jpg",
    description:
      "Empty your Gmail inbox with a GPT-3.5-powered extension that writes email replies. He understands: 🧠 specific details (add examples, questions, etc.) ❤️ sentiments (write politely, positively, etc.) 💎 form (add bullet points, tips, etc.) It's free!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 13601,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: -5069,
      growth_rate: -0.2715,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "ai-anywhere",
    name: "AI Anywhere",
    website: "https://www.ai-anywhere.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169287978720920543.jpg",
    description:
      "AI Anywhere is your ultimate desktop AI assistant that supercharges your productivity. It is your AI Copilot for all apps, not just websites. No more tedious copy-pasting is required when using ChatGPT!\n\nKey features:\n👉🏻Quick Action: Improve, summarize, translate, reply, and more with just a single click! It is seamlessly integrated with every app you use.\n💬Universal Chat: Simply press Option+Space to chat with AI anytime, anywhere.\n🚀AI Launcher: It comes with 50+ powerful AI commands. You can also add your own commands.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
      {
        handle: "code-assistant",
        name: "Code assistant",
        name_locales: {
          de: "Code-Assistent",
          en: "Code assistant",
          es: "Asistente de código",
          fr: "Assistant de code",
          ja: "コードアシスタント",
          ko: "코드 어시스턴트",
          pt: "Assistente de código",
          tw: "代碼助手",
          vi: "Trợ lý mã",
          zh: "代码辅助工具",
        },
        tool_count: 165,
      },
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "document-assistant",
        name: "Document Assistant",
        name_locales: {
          de: "Dokumentenassistent",
          en: "Document Assistant",
          es: "Asistente de documentos",
          fr: "Assistant de document",
          ja: "文書アシスタント",
          ko: "문서 도우미",
          pt: "Assistente de documentos",
          tw: "文件助手",
          vi: "Trợ lý tài liệu",
          zh: "文档助手",
        },
        tool_count: 187,
      },
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "general-writing",
        name: "General writing",
        name_locales: {
          de: "Allgemeine Schreibarbeit",
          en: "General writing",
          es: "Escritura general",
          fr: "Écriture générale",
          ja: "一般的な文章",
          ko: "일반적인 작성",
          pt: "Escrita geral",
          tw: "一般寫作",
          vi: "Viết chung",
          zh: "常规写作",
        },
        tool_count: 343,
      },
      {
        handle: "paraphraser",
        name: "Paraphraser",
        name_locales: {
          de: "Paraphrasierungsprogramm",
          en: "Paraphraser",
          es: "Paráfrasis",
          fr: "Paraphraseur",
          ja: "パラフレーザー",
          ko: "바꾸기 도구",
          pt: "Paráfrase",
          tw: "改寫工具",
          vi: "Công cụ thay đổi văn bản",
          zh: "改写工具",
        },
        tool_count: 38,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: [],
    month_visited_count: 88540,
    collected_count: 5,
    user_collected: 0,
    traffic: {
      top_region: "CN",
      top_region_value: 0.6282316152847135,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.8328573825263657,
        },
        {
          title: "Social",
          value: 0.06522532216750021,
        },
        {
          title: "Search",
          value: 0.05580315328593355,
        },
      ],
      growth: 77613,
      growth_rate: 7.1029,
      monthly_visits_mail: 901,
      monthly_visits_direct: 73741,
      monthly_visits_search: 4941,
      monthly_visits_social: 5775,
      monthly_visits_referrals: 3181,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "artificial-assistance",
    name: "Artificial assistance",
    website: "https://www.getbot.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169262174996288449.jpg",
    description:
      "Our goal with app is to optimize the use of the latest AI technology, making your life easier and more convenient!We have designed a smart solution that puts the power of AI right at your fingertips, eliminating the need for constantly switching between pages.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "image-generator",
        name: "Image generator",
        name_locales: {
          de: "Bildgenerator",
          en: "Image generator",
          es: "Generador de imágenes",
          fr: "Générateur d'images",
          ja: "画像生成器",
          ko: "이미지 생성기",
          pt: "Gerador de imagens",
          tw: "圖像生成器",
          vi: "Trình tạo hình ảnh",
          zh: "图像生成器",
        },
        tool_count: 298,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "chatgpt-add-in-for-outlook",
    name: "ChatGPT Add-in for Outlook",
    website: "https://www.chatgptoutlookaddin.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169253908848405747.jpg",
    description:
      "Blueberry has released a free Add-in for Microsoft Outlook, which allows users to experiment with ChatGPT within Outlook. The new Add-in allows users to configure custom prompts to run ChatGPT on selected email or new email.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "experiments",
        name: "Experiments",
        name_locales: {
          de: "Experimente",
          en: "Experiments",
          es: "Experimentos",
          fr: "Expériences",
          ja: "実験",
          ko: "실험",
          pt: "Experimentos",
          tw: "實驗",
          vi: "Thí nghiệm",
          zh: "实验",
        },
        tool_count: 49,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "cold-pitch",
    name: "Cold Pitch",
    website: "https://www.coldpitch.email",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169193530697951664.jpg",
    description:
      "Cold Pitch auto-creates personalized cold emails. Boost responses 3x-7x by using these dynamic openings.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "sales",
        name: "Sales",
        name_locales: {
          de: "Verkauf",
          en: "Sales",
          es: "Venta",
          fr: "Vente",
          ja: "セールス",
          ko: "판매",
          pt: "Vendas",
          tw: "銷售",
          vi: "Bán hàng",
          zh: "销售",
        },
        tool_count: 158,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "getsummary-tech",
    name: "GetSummary.tech",
    website: "https://getsummary.tech",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169164908083400937.jpg",
    description:
      "Introducing GetSummary.tech: Your time-saving AI email summary service. Just forward an email to us and get concise summaries in seconds, no extensions required! Stay informed and organized effortlessly, maximizing your efficiency.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "summarizer",
        name: "Summarizer",
        name_locales: {
          de: "Summarizer",
          en: "Summarizer",
          es: "Generador de resúmenes",
          fr: "Résumeur",
          ja: "要約作成ツール",
          ko: "요약 생성기",
          pt: "Resumidor",
          tw: "摘要產生器",
          vi: "Trình tóm tắt",
          zh: "摘要生成器",
        },
        tool_count: 196,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "ready-to-send",
    name: "Ready to Send",
    website: "https://getreadytosend.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169164901366454099.jpg",
    description:
      "Ready to Send is an AI-powered email assistant for Gmail that generates personalized draft replies automatically! Ready to Send works in the background, finding new emails and generating complete draft replies catered specifically to your unique conversations.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 302,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: -350,
      growth_rate: -0.5368,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "mailytic",
    name: "Mailytic",
    website: "https://mailytic.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169098403999031478.jpg",
    description:
      "1-step configuration email analytics, AI-driven automation and customers database. Made minimalist and easy to use for the whole team.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "waap",
    name: "WAAP",
    website: "https://www.waap-app.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169063114189063401.jpg",
    description:
      "We've developed an app that enables you to generate prospective dates and times, and input them into an email when planning meetings with clients. There's no longer a need to double-check if a date or day of the week is accurate.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 3,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "mailwave-ai",
    name: "Mailwave AI",
    website: "https://mailwave.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169039395092015592.jpg",
    description:
      "Mailwave AI is an intuitive, AI-powered email marketing tool. It simplifies campaign creation, automates workflows, optimizes deliver ability, and provides data analysis for improved targeting and conversion rates.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "gmail-gpt",
    name: "Gmail™ GPT",
    website:
      "https://workspace.google.com/marketplace/app/gmail_gpt/899305976589",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169021342271368674.jpg",
    description:
      "AI-enhanced assistant for streamlined email communication. Choose tones, shorten/lengthen emails, support for 30+ languages. Free, privacy-respecting, user-friendly.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Workspace",
            handle: "workspace",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 54363162,
    collected_count: 4,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.3131164561758221,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.391120132245879,
        },
        {
          title: "Search",
          value: 0.3402217357831111,
        },
        {
          title: "Referrals",
          value: 0.21826634156508257,
        },
      ],
      growth: -3446924,
      growth_rate: -0.0596,
      monthly_visits_mail: 110892,
      monthly_visits_direct: 21262527,
      monthly_visits_search: 18495529,
      monthly_visits_social: 1432828,
      monthly_visits_referrals: 11865648,
      monthly_visits_paid_referrals: 1195737,
      region_monthly_visits: null,
    },
  },
  {
    handle: "mailerlite-ai-drag-drop-editor",
    name: "MailerLite AI Drag & Drop Editor",
    website: "https://www.mailerlite.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169003638369892070.jpg",
    description:
      "Elevate newsletter creation with MailerLite's new email editor which includes an AI writing assistant for content and subject lines, inline editing, and custom block templates. Now anyone can design amazing layouts with messaging that resonates and converts.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 6740390,
    collected_count: 3,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.24772987539485147,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.7010142459419467,
        },
        {
          title: "Search",
          value: 0.13894990427872034,
        },
        {
          title: "Mail",
          value: 0.06799036901849374,
        },
      ],
      growth: 186341,
      growth_rate: 0.0284,
      monthly_visits_mail: 458282,
      monthly_visits_direct: 4725109,
      monthly_visits_search: 936577,
      monthly_visits_social: 285168,
      monthly_visits_referrals: 331832,
      monthly_visits_paid_referrals: 3423,
      region_monthly_visits: null,
    },
  },
  {
    handle: "aimailman",
    name: "AIMailman",
    website: "https://aimailman.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168987339079750316.jpg",
    description:
      "AI Mailman allows you to finely craft the most powerful emails in the world. Simply fill out a small form, and have a email template generated in seconds!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "alltum",
    name: "Alltum",
    website: "https://alltum.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168917905567550705.jpg",
    description:
      "The next generation of inbox. Alltum organizes your emails, tasks, files, and more so you can spend less time: Searching, Summarizing, & Coordinating.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 20857,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: "CL",
      top_region_value: 0.9551335653866172,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.899482182888129,
        },
        {
          title: "Search",
          value: 0.07519526559994925,
        },
        {
          title: "Referrals",
          value: 0.025322551511921743,
        },
      ],
      growth: -3463,
      growth_rate: -0.1424,
      monthly_visits_mail: 0,
      monthly_visits_direct: 18760,
      monthly_visits_search: 1568,
      monthly_visits_social: 0,
      monthly_visits_referrals: 528,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "show-by-animaker",
    name: "Show by Animaker",
    website: "https://www.getshow.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168900568040628625.jpg",
    description:
      "Show enables teams to deploy multi-touch attributed campaigns across product, web, email, and video. Whether you're looking to create Drip Campaigns, Newsletters, Video Emails, Transactional emails, or anything in between, Show has you covered. 👏",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 35950,
    collected_count: 11,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: -4928,
      growth_rate: -0.1206,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "mailbunny-ai",
    name: "MailBunny.ai",
    website: "https://mailbunny.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168863778137262334.jpg",
    description:
      "MailBunny.ai is your email-based AI-powered assistant!\n\nSummarize long emails, collaborate on content, and brainstorm new ideas with a ChatGPT-powered AI assistant always reachable via email.\n\nNo apps or plugins are needed, just send an email!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 0,
      growth_rate: 0,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "spam-message-filtering-ios",
    name: "Spam Message Filtering (iOS)",
    website: "https://apps.apple.com/us/app/spam-arrest-filter/id6450552880",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168863768547284127.jpg",
    description:
      "Say goodbye to the frustration of spam and the chaos of disorganized messages. Our app provides an intelligent solution that keeps your inbox clean, protects your personal info, and enhances your message management experience. Predicting spam is its forte.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "App",
            handle: "app",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 120973184,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.2498140453846545,
      top_traffic_sources: [
        {
          title: "Search",
          value: 0.3501868497890198,
        },
        {
          title: "Referrals",
          value: 0.29997363057480336,
        },
        {
          title: "Direct",
          value: 0.23186274514784305,
        },
      ],
      growth: 6295423,
      growth_rate: 0.0549,
      monthly_visits_mail: 1190477,
      monthly_visits_direct: 28049175,
      monthly_visits_search: 42363218,
      monthly_visits_social: 5059816,
      monthly_visits_referrals: 36288765,
      monthly_visits_paid_referrals: 8021734,
      region_monthly_visits: null,
    },
  },
  {
    handle: "gmplus",
    name: "GMPlus",
    website: "https://gmplus.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168821810262371153.jpg",
    description:
      "GMPlus, your AI Email Generator. Boost your Email writing and response efficiency by 10x with over 100 AI-generated prompts, multilingual output support, and custom template storage. Simplify and enhance your email writing process.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 27540,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 3767,
      growth_rate: 0.1585,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "angry-email-translator",
    name: "Angry Email Translator",
    website: "https://angryemailtranslator.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168804499093045609.jpg",
    description:
      "Angry Email Translator is a free AI tool that transforms your angry, paggro emails into polite and professional sounding ones. Even if you're upset at work, you can ensure your emails sound professional and avoid damaging relationships.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 506160,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: "RU",
      top_region_value: 0.504456182105358,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.5865875364494598,
        },
        {
          title: "Referrals",
          value: 0.24325141343923967,
        },
        {
          title: "Search",
          value: 0.10877369955608948,
        },
      ],
      growth: 240169,
      growth_rate: 0.9029,
      monthly_visits_mail: 0,
      monthly_visits_direct: 296907,
      monthly_visits_search: 55057,
      monthly_visits_social: 31072,
      monthly_visits_referrals: 123124,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
];
