export const Prompt = [
  {
    handle: "flot-ai",
    name: "Flot.ai",
    website: "https://flot.ai/?utm_source=toolify",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169357118260794822.jpg",
    description:
      "Flot.ai: AI Copilot for All Apps and Websites\n\nUse ChatGPT anywhere you type or select, On All Apps and Websites.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "document-assistant",
        name: "Document Assistant",
        name_locales: {
          de: "Dokumentenassistent",
          en: "Document Assistant",
          es: "Asistente de documentos",
          fr: "Assistant de document",
          ja: "文書アシスタント",
          ko: "문서 도우미",
          pt: "Assistente de documentos",
          tw: "文件助手",
          vi: "Trợ lý tài liệu",
          zh: "文档助手",
        },
        tool_count: 187,
      },
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "general-writing",
        name: "General writing",
        name_locales: {
          de: "Allgemeine Schreibarbeit",
          en: "General writing",
          es: "Escritura general",
          fr: "Écriture générale",
          ja: "一般的な文章",
          ko: "일반적인 작성",
          pt: "Escrita geral",
          tw: "一般寫作",
          vi: "Viết chung",
          zh: "常规写作",
        },
        tool_count: 343,
      },
      {
        handle: "paraphraser",
        name: "Paraphraser",
        name_locales: {
          de: "Paraphrasierungsprogramm",
          en: "Paraphraser",
          es: "Paráfrasis",
          fr: "Paraphraseur",
          ja: "パラフレーザー",
          ko: "바꾸기 도구",
          pt: "Paráfrase",
          tw: "改寫工具",
          vi: "Công cụ thay đổi văn bản",
          zh: "改写工具",
        },
        tool_count: 38,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "seo",
        name: "SEO",
        name_locales: {
          de: "SEO",
          en: "SEO",
          es: "SEO",
          fr: "SEO",
          ja: "検索エンジン最適化",
          ko: "검색 엔진 최적화",
          pt: "SEO",
          tw: "搜尋引擎最佳化",
          vi: "tối ưu hóa công cụ tìm kiếm",
          zh: "搜索引擎优化",
        },
        tool_count: 264,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "story-teller",
        name: "Story teller",
        name_locales: {
          de: "Geschichtenerzähler",
          en: "Story teller",
          es: "Cuentacuentos",
          fr: "Conteur d'histoires",
          ja: "語り部",
          ko: "이야기꾼",
          pt: "Contador de histórias",
          tw: "故事講述者",
          vi: "Người kể chuyện",
          zh: "讲故事人",
        },
        tool_count: 126,
      },
      {
        handle: "summarizer",
        name: "Summarizer",
        name_locales: {
          de: "Summarizer",
          en: "Summarizer",
          es: "Generador de resúmenes",
          fr: "Résumeur",
          ja: "要約作成ツール",
          ko: "요약 생성기",
          pt: "Resumidor",
          tw: "摘要產生器",
          vi: "Trình tóm tắt",
          zh: "摘要生成器",
        },
        tool_count: 196,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
      {
        handle: "pricing",
        name: "Pricing",
        options: [
          {
            name: "Paid",
            handle: "paid",
          },
          {
            name: "Free",
            handle: "free",
          },
        ],
      },
    ],
    prices: [],
    month_visited_count: 0,
    collected_count: 7,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "gen-expert",
    name: "Gen Expert",
    website: "https://genexpert.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454293895847019.jpg",
    description:
      "Supercharge your chatgpt experience with GenExpert. Unleash the power of customizable GPT models, captivating prompts, and documents with AI auto-completion. Effortlessly create top-notch content, save time, and enjoy ultimate privacy and security.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "general-writing",
        name: "General writing",
        name_locales: {
          de: "Allgemeine Schreibarbeit",
          en: "General writing",
          es: "Escritura general",
          fr: "Écriture générale",
          ja: "一般的な文章",
          ko: "일반적인 작성",
          pt: "Escrita geral",
          tw: "一般寫作",
          vi: "Viết chung",
          zh: "常规写作",
        },
        tool_count: 343,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "code-assistant",
        name: "Code assistant",
        name_locales: {
          de: "Code-Assistent",
          en: "Code assistant",
          es: "Asistente de código",
          fr: "Assistant de code",
          ja: "コードアシスタント",
          ko: "코드 어시스턴트",
          pt: "Assistente de código",
          tw: "代碼助手",
          vi: "Trợ lý mã",
          zh: "代码辅助工具",
        },
        tool_count: 165,
      },
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
      {
        handle: "document-assistant",
        name: "Document Assistant",
        name_locales: {
          de: "Dokumentenassistent",
          en: "Document Assistant",
          es: "Asistente de documentos",
          fr: "Assistant de document",
          ja: "文書アシスタント",
          ko: "문서 도우미",
          pt: "Assistente de documentos",
          tw: "文件助手",
          vi: "Trợ lý tài liệu",
          zh: "文档助手",
        },
        tool_count: 187,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "promptblocks",
    name: "Promptblocks",
    website: "https://promptblocks.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169416695165198637.jpg",
    description:
      "Social prompt engineering platform for AI app developers. Save, reuse, and refine your prompts, share with the community, and deploy your prompts effortlessly.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "promtify",
    name: "Promtify",
    website: "https://www.promtify.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169409379791351409.jpg",
    description:
      "With Promtify, you can turn complex prompts into easy-to-use templates, use them for work and entertainment, and even share them with the community.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "resources",
        name: "Resources",
        name_locales: {
          de: "Ressourcen",
          en: "Resources",
          es: "Recursos",
          fr: "Ressources",
          ja: "リソース",
          ko: "자원",
          pt: "Recursos",
          tw: "資源",
          vi: "Tài nguyên",
          zh: "资源",
        },
        tool_count: 67,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "chatgpt-free-and-unlimited-prompts",
    name: "ChatGPT Free and Unlimited Prompts",
    website: "https://chatgpt1s.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169401546166183136.jpg",
    description:
      "Get unlimited, free prompts and chat with ChatGPT without login required. Enjoy the freedom to seek assistance, explore ideas with ChatGPT hassle-free - ChatGPT1s.com",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "promptportals",
    name: "PromptPortals",
    website: "https://promptportals.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169348465439577976.jpg",
    description:
      "Manage and optimize AI prompts via API with analytics and user feedback.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "promptly-generated",
    name: "Promptly Generated",
    website: "https://promptlygenerated.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169340881274479496.jpg",
    description:
      "An AI Prompt engineer, simply enter your request, get the prompt, done. A streamlined, simple and affordable alternative to traditional prompt engineering, allowing anyone with a little, or alot of AI experience to generate powerful AI prompts for any LLM.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "artkey",
    name: "ArtKey",
    website: "https://www.artkey.cool",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169322530665472427.jpg",
    description:
      "Unlock Your Outstanding CreativityHigh-Quality Prompts Library For Midjourney",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "art",
        name: "Art",
        name_locales: {
          de: "Kunst",
          en: "Art",
          es: "Arte",
          fr: "Art",
          ja: "芸術",
          ko: "예술",
          pt: "Arte",
          tw: "藝術",
          vi: "Nghệ thuật",
          zh: "艺术",
        },
        tool_count: 398,
      },
      {
        handle: "design-assistant",
        name: "Design assistant",
        name_locales: {
          de: "Design-Assistent",
          en: "Design assistant",
          es: "Asistente de diseño",
          fr: "Assistant de conception",
          ja: "デザインアシスタント",
          ko: "디자인 어시스턴트",
          pt: "Assistente de design",
          tw: "設計助手",
          vi: "Trợ lý thiết kế",
          zh: "设计助手",
        },
        tool_count: 306,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 1013,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 1013,
      growth_rate: 0,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "glow-up-journal-coach",
    name: "Glow Up: Journal & Coach",
    website: "https://glowupjournal.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169313613092216858.jpg",
    description:
      "Introducing my new mobile app @_glowupjournal ☀️ it's a journaling app that also asks you questions. - easy journaling - get insights - have your glow up 👇 add a comment to get access to AI features",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "prompter",
    name: "Prompter",
    website: "https://prompter.engineer",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169295769378642523.jpg",
    description:
      "With Prompter, you can: 🚀 Send prompts to the API and view results ⚙️ Tweak parameters like temperature, top-p, etc. ⏳&nbsp;Save prompt history for later reference 🆚 Batch test prompts for efficient iteration",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "ai-anywhere",
    name: "AI Anywhere",
    website: "https://www.ai-anywhere.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169287978720920543.jpg",
    description:
      "AI Anywhere is your ultimate desktop AI assistant that supercharges your productivity. It is your AI Copilot for all apps, not just websites. No more tedious copy-pasting is required when using ChatGPT!\n\nKey features:\n👉🏻Quick Action: Improve, summarize, translate, reply, and more with just a single click! It is seamlessly integrated with every app you use.\n💬Universal Chat: Simply press Option+Space to chat with AI anytime, anywhere.\n🚀AI Launcher: It comes with 50+ powerful AI commands. You can also add your own commands.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
      {
        handle: "code-assistant",
        name: "Code assistant",
        name_locales: {
          de: "Code-Assistent",
          en: "Code assistant",
          es: "Asistente de código",
          fr: "Assistant de code",
          ja: "コードアシスタント",
          ko: "코드 어시스턴트",
          pt: "Assistente de código",
          tw: "代碼助手",
          vi: "Trợ lý mã",
          zh: "代码辅助工具",
        },
        tool_count: 165,
      },
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "document-assistant",
        name: "Document Assistant",
        name_locales: {
          de: "Dokumentenassistent",
          en: "Document Assistant",
          es: "Asistente de documentos",
          fr: "Assistant de document",
          ja: "文書アシスタント",
          ko: "문서 도우미",
          pt: "Assistente de documentos",
          tw: "文件助手",
          vi: "Trợ lý tài liệu",
          zh: "文档助手",
        },
        tool_count: 187,
      },
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "general-writing",
        name: "General writing",
        name_locales: {
          de: "Allgemeine Schreibarbeit",
          en: "General writing",
          es: "Escritura general",
          fr: "Écriture générale",
          ja: "一般的な文章",
          ko: "일반적인 작성",
          pt: "Escrita geral",
          tw: "一般寫作",
          vi: "Viết chung",
          zh: "常规写作",
        },
        tool_count: 343,
      },
      {
        handle: "paraphraser",
        name: "Paraphraser",
        name_locales: {
          de: "Paraphrasierungsprogramm",
          en: "Paraphraser",
          es: "Paráfrasis",
          fr: "Paraphraseur",
          ja: "パラフレーザー",
          ko: "바꾸기 도구",
          pt: "Paráfrase",
          tw: "改寫工具",
          vi: "Công cụ thay đổi văn bản",
          zh: "改写工具",
        },
        tool_count: 38,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: [],
    month_visited_count: 88540,
    collected_count: 5,
    user_collected: 0,
    traffic: {
      top_region: "CN",
      top_region_value: 0.6282316152847135,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.8328573825263657,
        },
        {
          title: "Social",
          value: 0.06522532216750021,
        },
        {
          title: "Search",
          value: 0.05580315328593355,
        },
      ],
      growth: 77613,
      growth_rate: 7.1029,
      monthly_visits_mail: 901,
      monthly_visits_direct: 73741,
      monthly_visits_search: 4941,
      monthly_visits_social: 5775,
      monthly_visits_referrals: 3181,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "chatgpt-add-in-for-outlook",
    name: "ChatGPT Add-in for Outlook",
    website: "https://www.chatgptoutlookaddin.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169253908848405747.jpg",
    description:
      "Blueberry has released a free Add-in for Microsoft Outlook, which allows users to experiment with ChatGPT within Outlook. The new Add-in allows users to configure custom prompts to run ChatGPT on selected email or new email.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "experiments",
        name: "Experiments",
        name_locales: {
          de: "Experimente",
          en: "Experiments",
          es: "Experimentos",
          fr: "Expériences",
          ja: "実験",
          ko: "실험",
          pt: "Experimentos",
          tw: "實驗",
          vi: "Thí nghiệm",
          zh: "实验",
        },
        tool_count: 49,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "promptport",
    name: "Promptport",
    website: "https://promptport.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169253846125051669.jpg",
    description:
      "PromptPort is a cutting-edge website that serves as a hub for all your prompt needs. With a user-friendly interface, it offers a wide range of features to enhance your AI tool experience.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 9270,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 9262,
      growth_rate: 1157.75,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "promptiz",
    name: "Promptiz",
    website: "https://promptiz.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169228009134163063.jpg",
    description:
      "Get Free Prompts for Every Interest on Promptiz! Ignite your creativity with a wide range of ideas for Writers,SEO, Artists, and more.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "general-writing",
        name: "General writing",
        name_locales: {
          de: "Allgemeine Schreibarbeit",
          en: "General writing",
          es: "Escritura general",
          fr: "Écriture générale",
          ja: "一般的な文章",
          ko: "일반적인 작성",
          pt: "Escrita geral",
          tw: "一般寫作",
          vi: "Viết chung",
          zh: "常规写作",
        },
        tool_count: 343,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "seo",
        name: "SEO",
        name_locales: {
          de: "SEO",
          en: "SEO",
          es: "SEO",
          fr: "SEO",
          ja: "検索エンジン最適化",
          ko: "검색 엔진 최적화",
          pt: "SEO",
          tw: "搜尋引擎最佳化",
          vi: "tối ưu hóa công cụ tìm kiếm",
          zh: "搜索引擎优化",
        },
        tool_count: 264,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 149,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 149,
      growth_rate: 0,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "complete-ai",
    name: "Complete AI",
    website:
      "https://chrome.google.com/webstore/detail/complete-ai-text-autocomp/fbmngedglhldachckegobogcglnbojge",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169193533218624678.jpg",
    description:
      "Chrome extension that helps you write prompts faster on ChatGPT with a single shortcut - and it's FREE!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Browser Extension",
            handle: "browser-extension",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 247136630,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.22191269346357223,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.8368373876173484,
        },
        {
          title: "Search",
          value: 0.08193425217161182,
        },
        {
          title: "Referrals",
          value: 0.06371080458066519,
        },
      ],
      growth: -2945035,
      growth_rate: -0.0118,
      monthly_visits_mail: 56903,
      monthly_visits_direct: 206813172,
      monthly_visits_search: 20248955,
      monthly_visits_social: 3399656,
      monthly_visits_referrals: 15745274,
      monthly_visits_paid_referrals: 872671,
      region_monthly_visits: null,
    },
  },
  {
    handle: "promptwave-ai",
    name: "PromptWave AI",
    website: "https://promptwave.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169193530719378545.jpg",
    description:
      "Lost in your AI prompts? 🤖 Introducing PromptWave AI! Your ultimate hub to save, organize, & rediscover AI prompts. 📑 Filter, sort, & reuse your gems. 🚀 Share your creations and witness their impact. 🌎 Dive in and get inspired by the community's masterpieces.🎨",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 781,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 781,
      growth_rate: 0,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "social-bellow",
    name: "Social Bellow",
    website: "https://www.socialbellow.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169166826129399030.jpg",
    description:
      "Revolutionize content with AI-powered prompts. Overcome writer's block, craft engaging narratives, and personalize chatbots. Elevate content strategy, brainstorm effortlessly, and resonate powerfully. Discover the next-gen content companion on Product Hunt!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "nixer-ai",
    name: "Nixer AI",
    website: "https://nixerai.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169164895073924315.jpg",
    description:
      '"Nixerai.com: A hub for 20,000+ Chat GPT prompts and 5000+ AI tools. Elevate your AI interactions and explore an AI-driven future with us."',
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 1384,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 1384,
      growth_rate: 0,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "blizzy",
    name: "Blizzy",
    website: "https://www.blizzy.app",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169116427710643395.jpg",
    description:
      "Tired of using different AI tools for chat, document search and online browsing? Introducing Blizzy 2.0, the secure AI assistant. It offers real-time internet browsing, a customizable knowledge base, ready-made prompts, and prioritizes privacy and security.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
      {
        handle: "document-assistant",
        name: "Document Assistant",
        name_locales: {
          de: "Dokumentenassistent",
          en: "Document Assistant",
          es: "Asistente de documentos",
          fr: "Assistant de document",
          ja: "文書アシスタント",
          ko: "문서 도우미",
          pt: "Assistente de documentos",
          tw: "文件助手",
          vi: "Trợ lý tài liệu",
          zh: "文档助手",
        },
        tool_count: 187,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 2945,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 2945,
      growth_rate: 0,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "redmo",
    name: "Redmo",
    website: "https://redmo.cc",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169116420356096437.jpg",
    description:
      "Redmo helps you run your prompts fast and repeatly by creating your own Prompt Templates with variables, workflow and API support. You can use Redmo to quickly run and share your prompts, and even build your own AI products or tools with our API.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "readyrunner",
    name: "ReadyRunner",
    website: "https://www.readyrunner.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169089660934786857.jpg",
    description:
      "ReadyRunner is a ChatGPT (GPT-3 and GPT-4) powered AI assistant app that runs on your desktop or the web. Use it to write, code, learn and be productive. ReadyRunner is full of design details and unique features including a prompt library and AI text editor.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "code-assistant",
        name: "Code assistant",
        name_locales: {
          de: "Code-Assistent",
          en: "Code assistant",
          es: "Asistente de código",
          fr: "Assistant de code",
          ja: "コードアシスタント",
          ko: "코드 어시스턴트",
          pt: "Assistente de código",
          tw: "代碼助手",
          vi: "Trợ lý mã",
          zh: "代码辅助工具",
        },
        tool_count: 165,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "dezee",
    name: "Dezee",
    website: "https://www.dezee.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169079780723968844.jpg",
    description:
      "Step into the future of innovation with Dezee, a cutting-edge AI tool redefining how we interact with technology. As your ultimate creative partner, it unleashes endless possibilities by seamlessly generating images, text, voice, transcripts, and summaries.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
      {
        handle: "art",
        name: "Art",
        name_locales: {
          de: "Kunst",
          en: "Art",
          es: "Arte",
          fr: "Art",
          ja: "芸術",
          ko: "예술",
          pt: "Arte",
          tw: "藝術",
          vi: "Nghệ thuật",
          zh: "艺术",
        },
        tool_count: 398,
      },
      {
        handle: "audio-editing",
        name: "Audio editing",
        name_locales: {
          de: "Audiobearbeitung",
          en: "Audio editing",
          es: "Edición de audio",
          fr: "Montage audio",
          ja: "オーディオ編集",
          ko: "오디오 편집",
          pt: "Edição de áudio",
          tw: "音訊編輯",
          vi: "Chỉnh sửa âm thanh",
          zh: "音频编辑",
        },
        tool_count: 109,
      },
      {
        handle: "code-assistant",
        name: "Code assistant",
        name_locales: {
          de: "Code-Assistent",
          en: "Code assistant",
          es: "Asistente de código",
          fr: "Assistant de code",
          ja: "コードアシスタント",
          ko: "코드 어시스턴트",
          pt: "Assistente de código",
          tw: "代碼助手",
          vi: "Trợ lý mã",
          zh: "代码辅助工具",
        },
        tool_count: 165,
      },
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "design-assistant",
        name: "Design assistant",
        name_locales: {
          de: "Design-Assistent",
          en: "Design assistant",
          es: "Asistente de diseño",
          fr: "Assistant de conception",
          ja: "デザインアシスタント",
          ko: "디자인 어시스턴트",
          pt: "Assistente de design",
          tw: "設計助手",
          vi: "Trợ lý thiết kế",
          zh: "设计助手",
        },
        tool_count: 306,
      },
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
      {
        handle: "document-assistant",
        name: "Document Assistant",
        name_locales: {
          de: "Dokumentenassistent",
          en: "Document Assistant",
          es: "Asistente de documentos",
          fr: "Assistant de document",
          ja: "文書アシスタント",
          ko: "문서 도우미",
          pt: "Assistente de documentos",
          tw: "文件助手",
          vi: "Trợ lý tài liệu",
          zh: "文档助手",
        },
        tool_count: 187,
      },
      {
        handle: "experiments",
        name: "Experiments",
        name_locales: {
          de: "Experimente",
          en: "Experiments",
          es: "Experimentos",
          fr: "Expériences",
          ja: "実験",
          ko: "실험",
          pt: "Experimentos",
          tw: "實驗",
          vi: "Thí nghiệm",
          zh: "实验",
        },
        tool_count: 49,
      },
      {
        handle: "general-writing",
        name: "General writing",
        name_locales: {
          de: "Allgemeine Schreibarbeit",
          en: "General writing",
          es: "Escritura general",
          fr: "Écriture générale",
          ja: "一般的な文章",
          ko: "일반적인 작성",
          pt: "Escrita geral",
          tw: "一般寫作",
          vi: "Viết chung",
          zh: "常规写作",
        },
        tool_count: 343,
      },
      {
        handle: "image-editing",
        name: "Image editing",
        name_locales: {
          de: "Bildbearbeitung",
          en: "Image editing",
          es: "Edición de imágenes",
          fr: "Édition d'images",
          ja: "画像編集",
          ko: "이미지 편집",
          pt: "Edição de imagem",
          tw: "影像編輯",
          vi: "Chỉnh sửa ảnh",
          zh: "影像编辑",
        },
        tool_count: 221,
      },
      {
        handle: "image-generator",
        name: "Image generator",
        name_locales: {
          de: "Bildgenerator",
          en: "Image generator",
          es: "Generador de imágenes",
          fr: "Générateur d'images",
          ja: "画像生成器",
          ko: "이미지 생성기",
          pt: "Gerador de imagens",
          tw: "圖像生成器",
          vi: "Trình tạo hình ảnh",
          zh: "图像生成器",
        },
        tool_count: 298,
      },
      {
        handle: "language-learning",
        name: "Language learning",
        name_locales: {
          de: "Sprachenlernen",
          en: "Language learning",
          es: "Aprendizaje de idiomas",
          fr: "Apprentissage des langues",
          ja: "言語学習",
          ko: "언어 학습",
          pt: "Aprendizagem de idiomas",
          tw: "語言學習",
          vi: "Học ngôn ngữ",
          zh: "语言学习",
        },
        tool_count: 235,
      },
      {
        handle: "logo-generator",
        name: "Logo generator",
        name_locales: {
          de: "Logo-Generator",
          en: "Logo generator",
          es: "Generador de logotipos",
          fr: "Générateur de logo",
          ja: "ロゴジェネレーター",
          ko: "로고 생성기",
          pt: "Gerador de logotipo",
          tw: "Logo產生器",
          vi: "Trình tạo logo",
          zh: "Logo生成器",
        },
        tool_count: 25,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "research",
        name: "Research",
        name_locales: {
          de: "Forschung",
          en: "Research",
          es: "Investigación",
          fr: "Recherche",
          ja: "研究",
          ko: "연구",
          pt: "Pesquisa",
          tw: "研究",
          vi: "Nghiên cứu",
          zh: "研究",
        },
        tool_count: 161,
      },
      {
        handle: "resources",
        name: "Resources",
        name_locales: {
          de: "Ressourcen",
          en: "Resources",
          es: "Recursos",
          fr: "Ressources",
          ja: "リソース",
          ko: "자원",
          pt: "Recursos",
          tw: "資源",
          vi: "Tài nguyên",
          zh: "资源",
        },
        tool_count: 67,
      },
      {
        handle: "seo",
        name: "SEO",
        name_locales: {
          de: "SEO",
          en: "SEO",
          es: "SEO",
          fr: "SEO",
          ja: "検索エンジン最適化",
          ko: "검색 엔진 최적화",
          pt: "SEO",
          tw: "搜尋引擎最佳化",
          vi: "tối ưu hóa công cụ tìm kiếm",
          zh: "搜索引擎优化",
        },
        tool_count: 264,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "story-teller",
        name: "Story teller",
        name_locales: {
          de: "Geschichtenerzähler",
          en: "Story teller",
          es: "Cuentacuentos",
          fr: "Conteur d'histoires",
          ja: "語り部",
          ko: "이야기꾼",
          pt: "Contador de histórias",
          tw: "故事講述者",
          vi: "Người kể chuyện",
          zh: "讲故事人",
        },
        tool_count: 126,
      },
      {
        handle: "summarizer",
        name: "Summarizer",
        name_locales: {
          de: "Summarizer",
          en: "Summarizer",
          es: "Generador de resúmenes",
          fr: "Résumeur",
          ja: "要約作成ツール",
          ko: "요약 생성기",
          pt: "Resumidor",
          tw: "摘要產生器",
          vi: "Trình tóm tắt",
          zh: "摘要生成器",
        },
        tool_count: 196,
      },
      {
        handle: "text-to-speech",
        name: "Text to speech",
        name_locales: {
          de: "Text-zu-Sprache",
          en: "Text to speech",
          es: "Texto a voz",
          fr: "Texte à parole",
          ja: "テキスト読み上げ",
          ko: "문장 읽어주기",
          pt: "Texto para fala",
          tw: "文本轉語音",
          vi: "Văn bản thành giọng nói",
          zh: "文本转语音",
        },
        tool_count: 181,
      },
      {
        handle: "transcriber",
        name: "Transcriber",
        name_locales: {
          de: "Transkriptor",
          en: "Transcriber",
          es: "Transcriptor",
          fr: "Transcripteur",
          ja: "音声認識者",
          ko: "전사자",
          pt: "Transcritor",
          tw: "轉錄員",
          vi: "Người chuyển văn bản",
          zh: "转录员",
        },
        tool_count: 134,
      },
      {
        handle: "video-generator",
        name: "Video generator",
        name_locales: {
          de: "Video-Generator",
          en: "Video generator",
          es: "Generador de videos",
          fr: "Générateur de vidéo",
          ja: "ビデオジェネレーター",
          ko: "비디오 생성기",
          pt: "Gerador de vídeos",
          tw: "影片產生器",
          vi: "Trình tạo video",
          zh: "视频生成器",
        },
        tool_count: 107,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 15937,
    collected_count: 3,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 12159,
      growth_rate: 3.2184,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "prompt-swipes-for-midjourney",
    name: "Prompt Swipes For Midjourney",
    website: "https://promptswipes.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169079775572714018.jpg",
    description:
      "Do you struggle with writing good prompts for Midjourney? The easiest way to make great looking images is to copy what works. Here you can swipe the best Midjourney prompts for and make your own stunning images.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 457,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: -27,
      growth_rate: -0.0558,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "pmtoolsai",
    name: "PMToolsAI",
    website: "https://www.pmtoolsai.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169053864227978988.jpg",
    description:
      "PMToolsAI is a collection of 30+ tools (AI prompts and execution) that help product managers with ideation, market sizing, defining the roadmap, north star metrics, SWOT analysis, JTBD statements, customer surveys, summarising feedback, and much more.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 15532,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 15532,
      growth_rate: 0,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "gaim-ai-desktop-app",
    name: "GAIM.AI Desktop App",
    website: "https://gaim.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169045637294244010.jpg",
    description:
      "GAIM.AI is your all-in-one AI superhub! Unleash the power of AI Personas, master coding with AI Dev Tools, and stir creativity with AI Image Generators. Search 100k+ prompts or create your own. Plus, get 10k FREE credits every month! 🚀 Look closely...🕵🏽",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "promptize",
    name: "Promptize",
    website: "https://www.promptize.co",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169029494681131125.jpg",
    description:
      "To implement the right AI tools in your company, you need the right prompts for ChatGPT and other models. We do that for you. AI Prompts as a Service. Stop overpaying for prompt engineers.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "ai-prompt-saver",
    name: "AI Prompt Saver",
    website:
      "https://chrome.google.com/webstore/detail/ai-prompt-saver/ipplfghnambhfflimmpbicbjhfgpfeoo",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169029483267924477.jpg",
    description:
      "☆ Save and re-use prompts ☆ Add prompts by selecting the text on a web page or via the extension toolbar button ☆ Store prompts securely in your browser only ☆ Insert prompts by right-clicking on a text input area",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Browser Extension",
            handle: "browser-extension",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 247136630,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.22191269346357223,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.8368373876173484,
        },
        {
          title: "Search",
          value: 0.08193425217161182,
        },
        {
          title: "Referrals",
          value: 0.06371080458066519,
        },
      ],
      growth: -2945035,
      growth_rate: -0.0118,
      monthly_visits_mail: 56903,
      monthly_visits_direct: 206813172,
      monthly_visits_search: 20248955,
      monthly_visits_social: 3399656,
      monthly_visits_referrals: 15745274,
      monthly_visits_paid_referrals: 872671,
      region_monthly_visits: null,
    },
  },
  {
    handle: "ai-prompt-search",
    name: "AI Prompt Search",
    website: "https://www.aipromptsearch.net",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169010635820609759.jpg",
    description:
      "Ai Prompt Search is The Best AI prompts For Models Like Stable Diffusion, ChatGPT, Midjourney",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 4604,
    collected_count: 3,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 4604,
      growth_rate: 0,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "shortcutsgpt",
    name: "ShortcutsGPT",
    website: "https://shortcutsgpt.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169008425817559856.jpg",
    description:
      "ShortcutsGPT allows you to create your own shortcuts for the repetitive prompts, so you don't waste your time telling ChatGPT to do the same thing repeatedly.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 14901,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 14901,
      growth_rate: 0,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "promptlocker",
    name: "PromptLocker",
    website: "https://www.promptlocker.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169003643924902298.jpg",
    description:
      "Ever found yourself lost in a sea of prompts, struggling to find that perfect one you saved for your AI models? With PromptLocker, you can store, categorize, and retrieve prompts for MidJourney, Stable Diffusion, Bard, and ChatGPT.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 1321,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 1187,
      growth_rate: 8.8582,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
];
