export const SocialMediaAssistant = [
  {
    handle: "flot-ai",
    name: "Flot.ai",
    website: "https://flot.ai/?utm_source=toolify",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169357118260794822.jpg",
    description:
      "Flot.ai: AI Copilot for All Apps and Websites\n\nUse ChatGPT anywhere you type or select, On All Apps and Websites.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "document-assistant",
        name: "Document Assistant",
        name_locales: {
          de: "Dokumentenassistent",
          en: "Document Assistant",
          es: "Asistente de documentos",
          fr: "Assistant de document",
          ja: "文書アシスタント",
          ko: "문서 도우미",
          pt: "Assistente de documentos",
          tw: "文件助手",
          vi: "Trợ lý tài liệu",
          zh: "文档助手",
        },
        tool_count: 187,
      },
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "general-writing",
        name: "General writing",
        name_locales: {
          de: "Allgemeine Schreibarbeit",
          en: "General writing",
          es: "Escritura general",
          fr: "Écriture générale",
          ja: "一般的な文章",
          ko: "일반적인 작성",
          pt: "Escrita geral",
          tw: "一般寫作",
          vi: "Viết chung",
          zh: "常规写作",
        },
        tool_count: 343,
      },
      {
        handle: "paraphraser",
        name: "Paraphraser",
        name_locales: {
          de: "Paraphrasierungsprogramm",
          en: "Paraphraser",
          es: "Paráfrasis",
          fr: "Paraphraseur",
          ja: "パラフレーザー",
          ko: "바꾸기 도구",
          pt: "Paráfrase",
          tw: "改寫工具",
          vi: "Công cụ thay đổi văn bản",
          zh: "改写工具",
        },
        tool_count: 38,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "seo",
        name: "SEO",
        name_locales: {
          de: "SEO",
          en: "SEO",
          es: "SEO",
          fr: "SEO",
          ja: "検索エンジン最適化",
          ko: "검색 엔진 최적화",
          pt: "SEO",
          tw: "搜尋引擎最佳化",
          vi: "tối ưu hóa công cụ tìm kiếm",
          zh: "搜索引擎优化",
        },
        tool_count: 264,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "story-teller",
        name: "Story teller",
        name_locales: {
          de: "Geschichtenerzähler",
          en: "Story teller",
          es: "Cuentacuentos",
          fr: "Conteur d'histoires",
          ja: "語り部",
          ko: "이야기꾼",
          pt: "Contador de histórias",
          tw: "故事講述者",
          vi: "Người kể chuyện",
          zh: "讲故事人",
        },
        tool_count: 126,
      },
      {
        handle: "summarizer",
        name: "Summarizer",
        name_locales: {
          de: "Summarizer",
          en: "Summarizer",
          es: "Generador de resúmenes",
          fr: "Résumeur",
          ja: "要約作成ツール",
          ko: "요약 생성기",
          pt: "Resumidor",
          tw: "摘要產生器",
          vi: "Trình tóm tắt",
          zh: "摘要生成器",
        },
        tool_count: 196,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
      {
        handle: "pricing",
        name: "Pricing",
        options: [
          {
            name: "Paid",
            handle: "paid",
          },
          {
            name: "Free",
            handle: "free",
          },
        ],
      },
    ],
    prices: [],
    month_visited_count: 0,
    collected_count: 7,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "hix-ai",
    name: "Hix AI",
    website: "https://hix.ai/?ref=yzqxndr6",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169054819035381052.jpg",
    description:
      "Generate high-quality copies for ads, emails, blogs, and more in seconds with HIX.AI, the most powerful, all-in-one AI writing copilot on the market.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "general-writing",
        name: "General writing",
        name_locales: {
          de: "Allgemeine Schreibarbeit",
          en: "General writing",
          es: "Escritura general",
          fr: "Écriture générale",
          ja: "一般的な文章",
          ko: "일반적인 작성",
          pt: "Escrita geral",
          tw: "一般寫作",
          vi: "Viết chung",
          zh: "常规写作",
        },
        tool_count: 343,
      },
      {
        handle: "paraphraser",
        name: "Paraphraser",
        name_locales: {
          de: "Paraphrasierungsprogramm",
          en: "Paraphraser",
          es: "Paráfrasis",
          fr: "Paraphraseur",
          ja: "パラフレーザー",
          ko: "바꾸기 도구",
          pt: "Paráfrase",
          tw: "改寫工具",
          vi: "Công cụ thay đổi văn bản",
          zh: "改写工具",
        },
        tool_count: 38,
      },
      {
        handle: "seo",
        name: "SEO",
        name_locales: {
          de: "SEO",
          en: "SEO",
          es: "SEO",
          fr: "SEO",
          ja: "検索エンジン最適化",
          ko: "검색 엔진 최적화",
          pt: "SEO",
          tw: "搜尋引擎最佳化",
          vi: "tối ưu hóa công cụ tìm kiếm",
          zh: "搜索引擎优化",
        },
        tool_count: 264,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "summarizer",
        name: "Summarizer",
        name_locales: {
          de: "Summarizer",
          en: "Summarizer",
          es: "Generador de resúmenes",
          fr: "Résumeur",
          ja: "要約作成ツール",
          ko: "요약 생성기",
          pt: "Resumidor",
          tw: "摘要產生器",
          vi: "Trình tóm tắt",
          zh: "摘要生成器",
        },
        tool_count: 196,
      },
      {
        handle: "e-commerce",
        name: "E-commerce",
        name_locales: {
          de: "E-Commerce",
          en: "E-commerce",
          es: "Comercio electrónico",
          fr: "Commerce électronique",
          ja: "Eコマース",
          ko: "전자상거래",
          pt: "Comércio eletrônico",
          tw: "電子商務",
          vi: "Thương mại điện tử",
          zh: "电子商务",
        },
        tool_count: 215,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
      {
        handle: "pricing",
        name: "Pricing",
        options: [
          {
            name: "Paid",
            handle: "paid",
          },
          {
            name: "Free",
            handle: "free",
          },
        ],
      },
    ],
    prices: [],
    month_visited_count: 19250,
    collected_count: 32,
    user_collected: 0,
    traffic: {
      top_region: "HK",
      top_region_value: 0.3944464310670012,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.6501487715922396,
        },
        {
          title: "Search",
          value: 0.19105278875881593,
        },
        {
          title: "Mail",
          value: 0.0842600773322923,
        },
      ],
      growth: -18593,
      growth_rate: -0.4913,
      monthly_visits_mail: 1622,
      monthly_visits_direct: 12515,
      monthly_visits_search: 3678,
      monthly_visits_social: 0,
      monthly_visits_referrals: 1435,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "thumbmachine",
    name: "Thumbmachine",
    website: "https://thumbmachine.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454285045558313.jpg",
    description:
      "Introducing Thumbmachine - The Ultimate Online Thumbnail Design Tool! With the power of AI and a vast library of customizable design styles, Thumbmachine helps you create professional thumbnails, social media posts, and marketing designs in just a few clicks.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "design-assistant",
        name: "Design assistant",
        name_locales: {
          de: "Design-Assistent",
          en: "Design assistant",
          es: "Asistente de diseño",
          fr: "Assistant de conception",
          ja: "デザインアシスタント",
          ko: "디자인 어시스턴트",
          pt: "Assistente de design",
          tw: "設計助手",
          vi: "Trợ lý thiết kế",
          zh: "设计助手",
        },
        tool_count: 306,
      },
      {
        handle: "image-editing",
        name: "Image editing",
        name_locales: {
          de: "Bildbearbeitung",
          en: "Image editing",
          es: "Edición de imágenes",
          fr: "Édition d'images",
          ja: "画像編集",
          ko: "이미지 편집",
          pt: "Edição de imagem",
          tw: "影像編輯",
          vi: "Chỉnh sửa ảnh",
          zh: "影像编辑",
        },
        tool_count: 221,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 3070,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 1381,
      growth_rate: 0.8176,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "rapidely",
    name: "rapidely",
    website: "https://rapidely.app",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454281654441979.jpg",
    description:
      "Meet Rapidely, your AI assistant for social media management. It's designed to support you in creating your tailored strategy, generating custom content ideas, crafting captions, designing carousels, and scheduling posts, enhancing your creative process.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 17207,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: "FR",
      top_region_value: 0.38445866833861286,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.5553981708745824,
        },
        {
          title: "Search",
          value: 0.26140955617110934,
        },
        {
          title: "Referrals",
          value: 0.11846915298617908,
        },
      ],
      growth: 5271,
      growth_rate: 0.4416,
      monthly_visits_mail: 427,
      monthly_visits_direct: 9557,
      monthly_visits_search: 4498,
      monthly_visits_social: 686,
      monthly_visits_referrals: 2038,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "image-to-caption",
    name: "Image to Caption",
    website: "https://image-to-caption.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454163920616117.jpg",
    description:
      "Effortlessly create captivating captions with our cutting-edge AI-Powered image to caption generator. Designed for social media posts, blog articles, and a range of content. Enhance engagement, save time, and elevate your online presence seamlessly.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "social-scanner",
    name: "Social Scanner",
    website: "https://www.socialscanner.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169409380879832482.jpg",
    description:
      "SocialScanner is your LinkedIn networking assistant. It helps you create personalized messages, increase response rates, and save time connecting with professionals in your industry.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "chatme-at",
    name: "ChatMe.At",
    website: "https://chatme.at",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169401548764007671.jpg",
    description:
      "Indulge in mesmerizing and thought-provoking conversations with the content creators you hold closest to your heart, interactions that will effortlessly captivate your senses and have you yearning for even more. 🌟",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "reachifyme",
    name: "ReachifyMe",
    website: "https://reachifyme.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169384067072762355.jpg",
    description:
      "AI tool to build a personal brand and monetise on LinkedIn. We help you by taking end-to-end care of your personal brand, without you getting a burnout.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 12,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "emoji-combiner",
    name: "Emoji Combiner",
    website: "https://emojicombiner.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169374136029672000.jpg",
    description:
      "🥳 Introducing Emoji Combiner! Mix any 2 emojis together to create a brand new one with our user-friendly online tool. Share your creations on social media, download them, or copy to clipboard. Powered by Google Emoji Kitchen. Elevate your emoji game today.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "fun-tools",
        name: "Fun tools",
        name_locales: {
          de: "Spaßwerkzeuge",
          en: "Fun tools",
          es: "Herramientas divertidas",
          fr: "Outils amusants",
          ja: "楽しいツール",
          ko: "재미있는 도구",
          pt: "Ferramentas divertidas",
          tw: "有趣工具",
          vi: "Công cụ vui nhộn",
          zh: "趣味工具",
        },
        tool_count: 197,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "metana",
    name: "METANA",
    website: "https://metana.press",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169374136056742987.jpg",
    description:
      "METANA turns overloaded info into overviews. Currently it supports RSS as an info source, and will soon support other major social media such as X (Twitter) and Discord, making it suitable for newsletter writers, readers, or researchers.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "research",
        name: "Research",
        name_locales: {
          de: "Forschung",
          en: "Research",
          es: "Investigación",
          fr: "Recherche",
          ja: "研究",
          ko: "연구",
          pt: "Pesquisa",
          tw: "研究",
          vi: "Nghiên cứu",
          zh: "研究",
        },
        tool_count: 161,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "repost-ai-instagram-tiktok-twitter",
    name: "Repost AI : Instagram - Tiktok - Twitter",
    website: "https://apps.apple.com/app/apple-store/id1456765672",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169374132796521186.jpg",
    description:
      "The #1 Repost app makes it easy to share photos and videos across profiles and social media platforms. Repost allows you to save and collect photos, videos, stories, highlights, and reels on Instagram, TikTok, and Twitter.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "App",
            handle: "app",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 118449982,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.24253346927315403,
      top_traffic_sources: [
        {
          title: "Search",
          value: 0.34298605945565247,
        },
        {
          title: "Referrals",
          value: 0.31164588745370364,
        },
        {
          title: "Direct",
          value: 0.23273471611265417,
        },
      ],
      growth: -2523202,
      growth_rate: -0.0209,
      monthly_visits_mail: 1295492,
      monthly_visits_direct: 27567423,
      monthly_visits_search: 40626693,
      monthly_visits_social: 4189658,
      monthly_visits_referrals: 36914450,
      monthly_visits_paid_referrals: 7856266,
      region_monthly_visits: null,
    },
  },
  {
    handle: "clipgen",
    name: "ClipGen",
    website: "https://www.clipgen.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169373360044494072.jpg",
    description:
      "ClipGen takes your long-form podcast content and creates 10-12 short-form clips that are optimized for discoverability on social media platforms. We support both video and audio podcasts, adding subtitles, custom branding, and support 30+ languages.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "audio-editing",
        name: "Audio editing",
        name_locales: {
          de: "Audiobearbeitung",
          en: "Audio editing",
          es: "Edición de audio",
          fr: "Montage audio",
          ja: "オーディオ編集",
          ko: "오디오 편집",
          pt: "Edição de áudio",
          tw: "音訊編輯",
          vi: "Chỉnh sửa âm thanh",
          zh: "音频编辑",
        },
        tool_count: 109,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 2236,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 2063,
      growth_rate: 11.9249,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "viralheadline-net",
    name: "ViralHeadline.net",
    website: "https://viralheadline.net",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169357219177946430.jpg",
    description:
      "ViralHeadline.net is a content headline generator for your blog posts, podcasts, newsletters, YouTube videos and more. Simply describe your content and platform and copy and paste.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "social-media-bio-generator",
    name: "Social Media Bio Generator",
    website: "https://socialmediabiogenerator.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169357215295865323.jpg",
    description:
      "The Social Media Bio Generator helps users craft unique and tailored bios for different platforms. With customization options like tone, type, and language, it ensures each bio is a perfect fit for its intended audience and platform.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "buildinpublic-ai",
    name: "Buildinpublic.ai",
    website: "https://www.buildinpublic.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169340881040334617.jpg",
    description:
      "Buildinpublic.ai - Elevate your product journey with indie-friendly tools. We give indie hackers tools to showcase progress, engage with a feedback-rich community, and cultivate an audience even before launch. Your journey to success, shared and supported!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "developer-tools",
        name: "Developer tools",
        name_locales: {
          de: "Entwickler-Tools",
          en: "Developer tools",
          es: "Developer tools",
          fr: "Outils de développement",
          ja: "開発者ツール",
          ko: "개발자 도구",
          pt: "Developer tools",
          tw: "開發人員工具",
          vi: "Công cụ phát triển",
          zh: "开发者工具",
        },
        tool_count: 562,
      },
      {
        handle: "startup-tools",
        name: "Startup tools",
        name_locales: {
          de: "Startup-Tools",
          en: "Startup tools",
          es: "Herramientas para startups",
          fr: "Outils de démarrage",
          ja: "スタートアップツール",
          ko: "스타트업 도구",
          pt: "Ferramentas para startups",
          tw: "啟動工具",
          vi: "Công cụ khởi nghiệp",
          zh: "初创企业工具",
        },
        tool_count: 188,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "avatar",
    name: "Avatar",
    website: "https://www.twitter-avatar.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169340878559736800.jpg",
    description:
      "Avatar is a tool that leverages state of art AI to make your icons alive in digital realm based on their real tweets in an accessible and factual manner.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "avatars",
        name: "Avatars",
        name_locales: {
          de: "Avatare",
          en: "Avatars",
          es: "Avatares",
          fr: "Avatars",
          ja: "アバター",
          ko: "아바타",
          pt: "Avatares",
          tw: "頭像",
          vi: "Ảnh đại diện",
          zh: "头像",
        },
        tool_count: 95,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 629,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 629,
      growth_rate: 0,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "linkedly",
    name: "Linkedly",
    website: "https://linkedly.app",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169340876530882218.jpg",
    description:
      "Personalizes your outreach using ChatGPT - Scans profile to create a personalized message - Finds possible email addresses using Hunter.io - Ability to download generated connections to Excel",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "sales",
        name: "Sales",
        name_locales: {
          de: "Verkauf",
          en: "Sales",
          es: "Venta",
          fr: "Vente",
          ja: "セールス",
          ko: "판매",
          pt: "Vendas",
          tw: "銷售",
          vi: "Bán hàng",
          zh: "销售",
        },
        tool_count: 158,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "replymind",
    name: "ReplyMind",
    website: "https://www.replymind.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169330348289830504.jpg",
    description:
      "ReplyMind is an AI tool that helps busy professionals grow their social presence in the most organic way on LinkedIn, X (Twitter), and Product Hunt by generating authentic, thoughtful & relevant replies in seconds.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "wunderwrite",
    name: "Wunderwrite",
    website: "https://wunderwrite.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169295798294258279.jpg",
    description:
      "Upload a photo and let Wunderwrite's advanced AI analyze it, suggest keywords, and consider your emotions to craft the ideal caption. Wunderwrite is your personal Social Media Marketing manager available anytime at your fingertips.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "writeturbo",
    name: "WriteTurbo",
    website: "https://writeturbo.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169295779368806084.jpg",
    description:
      "WriteTurbo allows for users to affordably generate quality Facebook ads, Instagram ads, Google ads, Social media posts, SEO optimized Content, Blogs, Articles and more, using AI!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "seo",
        name: "SEO",
        name_locales: {
          de: "SEO",
          en: "SEO",
          es: "SEO",
          fr: "SEO",
          ja: "検索エンジン最適化",
          ko: "검색 엔진 최적화",
          pt: "SEO",
          tw: "搜尋引擎最佳化",
          vi: "tối ưu hóa công cụ tìm kiếm",
          zh: "搜索引擎优化",
        },
        tool_count: 264,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 3,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "klipme",
    name: "Klipme",
    website: "https://klipmeapp.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169295779451788045.jpg",
    description:
      "Klipme is an AI video editor designed to streamline the editing process. Have AI analyze your longer videos and choose the best moments for a competition. Up your promotion or social media game with AI content.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 3136,
    collected_count: 5,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 2181,
      growth_rate: 2.2838,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "branalyzer-brand-s-instant-analyzer",
    name: "Branalyzer Brand's Instant Analyzer",
    website:
      "https://chrome.google.com/webstore/detail/branalyzer-brands-instant/kanpedinmjgnofkklpefdkcbbobifkdh",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169295772842227810.jpg",
    description:
      "Analyze Brand traffic and key metrics for any website, including SEO, Competitors, Social metrics, Ads, Emails, and Truspilot...in less than a minute. Branalyzer Chrome Extension allows you to find relevant information about each brand instantly.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "seo",
        name: "SEO",
        name_locales: {
          de: "SEO",
          en: "SEO",
          es: "SEO",
          fr: "SEO",
          ja: "検索エンジン最適化",
          ko: "검색 엔진 최적화",
          pt: "SEO",
          tw: "搜尋引擎最佳化",
          vi: "tối ưu hóa công cụ tìm kiếm",
          zh: "搜索引擎优化",
        },
        tool_count: 264,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Browser Extension",
            handle: "browser-extension",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 256460079,
    collected_count: 3,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.2194574601803874,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.8377551073278602,
        },
        {
          title: "Search",
          value: 0.07984549844417992,
        },
        {
          title: "Referrals",
          value: 0.06527295668248258,
        },
      ],
      growth: 9323449,
      growth_rate: 0.0377,
      monthly_visits_mail: 157000,
      monthly_visits_direct: 214850741,
      monthly_visits_search: 20477183,
      monthly_visits_social: 3080286,
      monthly_visits_referrals: 16739908,
      monthly_visits_paid_referrals: 1154962,
      region_monthly_visits: null,
    },
  },
  {
    handle: "metoo-camera-iphone-app",
    name: "MeToo Camera iPhone App",
    website: "https://apps.apple.com/us/app/metoo-camera/id6461267924",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169295743213774320.jpg",
    description:
      'Presenting "MeToo Camera" - Capture moments together! Say goodbye to missing in photos. Dual inside-outside cameras, drag-adjustable views, square/circular frames, videos. Instant sharing. For iPhone XS and newer. Join moments with "MeToo Camera"!',
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "image-editing",
        name: "Image editing",
        name_locales: {
          de: "Bildbearbeitung",
          en: "Image editing",
          es: "Edición de imágenes",
          fr: "Édition d'images",
          ja: "画像編集",
          ko: "이미지 편집",
          pt: "Edição de imagem",
          tw: "影像編輯",
          vi: "Chỉnh sửa ảnh",
          zh: "影像编辑",
        },
        tool_count: 221,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "App",
            handle: "app",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 118449982,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.24253346927315403,
      top_traffic_sources: [
        {
          title: "Search",
          value: 0.34298605945565247,
        },
        {
          title: "Referrals",
          value: 0.31164588745370364,
        },
        {
          title: "Direct",
          value: 0.23273471611265417,
        },
      ],
      growth: -2523202,
      growth_rate: -0.0209,
      monthly_visits_mail: 1295492,
      monthly_visits_direct: 27567423,
      monthly_visits_search: 40626693,
      monthly_visits_social: 4189658,
      monthly_visits_referrals: 36914450,
      monthly_visits_paid_referrals: 7856266,
      region_monthly_visits: null,
    },
  },
  {
    handle: "ad-mocker",
    name: "Ad Mocker",
    website: "https://admocker.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169295741285338339.jpg",
    description:
      "With Ad Mocker at your fingertips, easily create stunning previews for Facebook, Instagram, Google Display Network, and YouTube. Craft visually captivating ads with dynamic elements effortlessly.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "design-assistant",
        name: "Design assistant",
        name_locales: {
          de: "Design-Assistent",
          en: "Design assistant",
          es: "Asistente de diseño",
          fr: "Assistant de conception",
          ja: "デザインアシスタント",
          ko: "디자인 어시스턴트",
          pt: "Assistente de design",
          tw: "設計助手",
          vi: "Trợ lý thiết kế",
          zh: "设计助手",
        },
        tool_count: 306,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 3860,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 3860,
      growth_rate: 0,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "ai-anywhere",
    name: "AI Anywhere",
    website: "https://www.ai-anywhere.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169287978720920543.jpg",
    description:
      "AI Anywhere is your ultimate desktop AI assistant that supercharges your productivity. It is your AI Copilot for all apps, not just websites. No more tedious copy-pasting is required when using ChatGPT!\n\nKey features:\n👉🏻Quick Action: Improve, summarize, translate, reply, and more with just a single click! It is seamlessly integrated with every app you use.\n💬Universal Chat: Simply press Option+Space to chat with AI anytime, anywhere.\n🚀AI Launcher: It comes with 50+ powerful AI commands. You can also add your own commands.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
      {
        handle: "code-assistant",
        name: "Code assistant",
        name_locales: {
          de: "Code-Assistent",
          en: "Code assistant",
          es: "Asistente de código",
          fr: "Assistant de code",
          ja: "コードアシスタント",
          ko: "코드 어시스턴트",
          pt: "Assistente de código",
          tw: "代碼助手",
          vi: "Trợ lý mã",
          zh: "代码辅助工具",
        },
        tool_count: 165,
      },
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "document-assistant",
        name: "Document Assistant",
        name_locales: {
          de: "Dokumentenassistent",
          en: "Document Assistant",
          es: "Asistente de documentos",
          fr: "Assistant de document",
          ja: "文書アシスタント",
          ko: "문서 도우미",
          pt: "Assistente de documentos",
          tw: "文件助手",
          vi: "Trợ lý tài liệu",
          zh: "文档助手",
        },
        tool_count: 187,
      },
      {
        handle: "email-assistant",
        name: "Email assistant",
        name_locales: {
          de: "E-Mail-Assistent",
          en: "Email assistant",
          es: "Asistente de correo electrónico",
          fr: "Assistant de messagerie électronique",
          ja: "電子メールアシスタント",
          ko: "이메일 도우미",
          pt: "Assistente de e-mail",
          tw: "電子郵件助手",
          vi: "Trợ lý email",
          zh: "电子邮件助手",
        },
        tool_count: 187,
      },
      {
        handle: "general-writing",
        name: "General writing",
        name_locales: {
          de: "Allgemeine Schreibarbeit",
          en: "General writing",
          es: "Escritura general",
          fr: "Écriture générale",
          ja: "一般的な文章",
          ko: "일반적인 작성",
          pt: "Escrita geral",
          tw: "一般寫作",
          vi: "Viết chung",
          zh: "常规写作",
        },
        tool_count: 343,
      },
      {
        handle: "paraphraser",
        name: "Paraphraser",
        name_locales: {
          de: "Paraphrasierungsprogramm",
          en: "Paraphraser",
          es: "Paráfrasis",
          fr: "Paraphraseur",
          ja: "パラフレーザー",
          ko: "바꾸기 도구",
          pt: "Paráfrase",
          tw: "改寫工具",
          vi: "Công cụ thay đổi văn bản",
          zh: "改写工具",
        },
        tool_count: 38,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "prompts",
        name: "Prompts",
        name_locales: {
          de: "Aufforderungen",
          en: "Prompts",
          es: "Indicaciones",
          fr: "Messages",
          ja: "プロンプト",
          ko: "알림",
          pt: "Instruções",
          tw: "提示",
          vi: "Lời nhắc",
          zh: "提示",
        },
        tool_count: 173,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: [],
    month_visited_count: 88540,
    collected_count: 5,
    user_collected: 0,
    traffic: {
      top_region: "CN",
      top_region_value: 0.6282316152847135,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.8328573825263657,
        },
        {
          title: "Social",
          value: 0.06522532216750021,
        },
        {
          title: "Search",
          value: 0.05580315328593355,
        },
      ],
      growth: 77613,
      growth_rate: 7.1029,
      monthly_visits_mail: 901,
      monthly_visits_direct: 73741,
      monthly_visits_search: 4941,
      monthly_visits_social: 5775,
      monthly_visits_referrals: 3181,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "captionslab",
    name: "CaptionsLab",
    website: "https://www.captionslab.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169253915341149936.jpg",
    description:
      "CaptionsLab.com is a cutting-edge online AI platform that revolutionizes the way you create Instagram & TikTok Captions. In under 1 minute, create facinating captions that fit your mood!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "driftroom",
    name: "Driftroom",
    website: "https://www.driftroom.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169253916976341700.jpg",
    description:
      "Driftroom is a new Ai powered group chat community that helps you easily make new friends or spark up a romantic encounter! Driftroom helps you make real connections based on your profile, interests and how you chat, not with fake profiles or flashy photos.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "dating",
        name: "Dating",
        name_locales: {
          de: "Dating",
          en: "Dating",
          es: "Citas",
          fr: "Rendez-vous amoureux",
          ja: "デート",
          ko: "데이트",
          pt: "Encontros",
          tw: "約會",
          vi: "Hẹn hò",
          zh: "约会",
        },
        tool_count: 63,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "chappie-cm",
    name: "Chappie CM",
    website: "https://chappie.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169253915120202399.jpg",
    description:
      "World's 1st Community Moderator Companion! Do you remember how painful it is to manage a Community team? 💀 Think of Chappie as your go-to bot for building and managing a Telegram community🚀",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "viraldashboard",
    name: "ViralDashboard",
    website: "https://viraldashboard.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169228003533294428.jpg",
    description:
      "ViralDashboard is a cutting-edge AI-powered social media management tool designed to help businesses and influencers effectively manage, monitor, and optimize their social media presence.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 21157,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: "MX",
      top_region_value: 0.703011769906622,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.8522433380690302,
        },
        {
          title: "Social",
          value: 0.08252726611185701,
        },
        {
          title: "Search",
          value: 0.03877224182905533,
        },
      ],
      growth: 15801,
      growth_rate: 2.9501,
      monthly_visits_mail: 0,
      monthly_visits_direct: 18031,
      monthly_visits_search: 820,
      monthly_visits_social: 1746,
      monthly_visits_referrals: 535,
      monthly_visits_paid_referrals: 25,
      region_monthly_visits: null,
    },
  },
  {
    handle: "ai-socialbot",
    name: "Ai Socialbot",
    website:
      "https://play.google.com/store/apps/details?id=ai.cimple.cooltexts",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169220580494923602.jpg",
    description:
      '"Elevate content creation with AI Socialbot: the ultimate AI-powered solution for effortless message crafting. Revolutionize social media engagement using cutting-edge GPT tech. Personalized greetings, captions, LinkedIn & Twitter posts made easy.',
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "App",
            handle: "app",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 1104526458,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.17000735102859063,
      top_traffic_sources: [
        {
          title: "Search",
          value: 0.3826995191499246,
        },
        {
          title: "Direct",
          value: 0.3687108684165375,
        },
        {
          title: "Referrals",
          value: 0.17145414884256224,
        },
      ],
      growth: 3385911,
      growth_rate: 0.0031,
      monthly_visits_mail: 3706966,
      monthly_visits_direct: 407250910,
      monthly_visits_search: 422701744,
      monthly_visits_social: 53056339,
      monthly_visits_referrals: 189375644,
      monthly_visits_paid_referrals: 28434855,
      region_monthly_visits: null,
    },
  },
];
