export const videoEdit = [
  {
    handle: "deadale-language-translation",
    name: "Deadale Language Translation",
    website: "https://deadale.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454282660451724.jpg",
    description:
      "Meet Deadale Translation: an AI-powered tool aimed at breaking down video language barriers by instantly translating any marketing video to 10+ languages. Within 5 mins and without code, reach global audiences with your video.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "language-learning",
        name: "Language learning",
        name_locales: {
          de: "Sprachenlernen",
          en: "Language learning",
          es: "Aprendizaje de idiomas",
          fr: "Apprentissage des langues",
          ja: "言語学習",
          ko: "언어 학습",
          pt: "Aprendizagem de idiomas",
          tw: "語言學習",
          vi: "Học ngôn ngữ",
          zh: "语言学习",
        },
        tool_count: 235,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "maekersuite",
    name: "Maekersuite",
    website: "https://maekersuite.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454276676617182.jpg",
    description:
      "With Maekersuite, you can generate 1-15 minute ready-to-record optimised YouTube scripts from content briefs. Discover top content and analyse your niche with our improved Content Explorer and edit scripts interactively with our new Ask-AI feature.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 57434,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 9108,
      growth_rate: 0.1885,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "swapface-org",
    name: "Swapface.org",
    website: "https://www.swapface.org",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169454163788394429.jpg",
    description:
      "Swapface is a real-time and ultra realistic faceswap AI app which allows users to instantly transform into anyone with a single photo without any processing time. It's easy to set up and lets you take your content creation, live streaming to a new level.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "image-editing",
        name: "Image editing",
        name_locales: {
          de: "Bildbearbeitung",
          en: "Image editing",
          es: "Edición de imágenes",
          fr: "Édition d'images",
          ja: "画像編集",
          ko: "이미지 편집",
          pt: "Edição de imagem",
          tw: "影像編輯",
          vi: "Chỉnh sửa ảnh",
          zh: "影像编辑",
        },
        tool_count: 221,
      },
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 439998,
    collected_count: 0,
    user_collected: 0,
    traffic: {
      top_region: "CN",
      top_region_value: 0.20915138199328484,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.3838777437468437,
        },
        {
          title: "Search",
          value: 0.29655813282246796,
        },
        {
          title: "Social",
          value: 0.19615884784671633,
        },
      ],
      growth: 45214,
      growth_rate: 0.1145,
      monthly_visits_mail: 774,
      monthly_visits_direct: 168905,
      monthly_visits_search: 130485,
      monthly_visits_social: 86310,
      monthly_visits_referrals: 53240,
      monthly_visits_paid_referrals: 284,
      region_monthly_visits: null,
    },
  },
  {
    handle: "snipo",
    name: "Snipo",
    website: "https://snipo.io",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169392410541132545.jpg",
    description:
      "📝 Take timestamped notes directly in Notion while watching videos and effortlessly sync with course content as you navigate through the material. Enjoy split mode, take screenshots, and capture video clips. 📚Level up your knowledge with AI flashcards!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "education-assistant",
        name: "Education assistant",
        name_locales: {
          de: "Bildungsassistent",
          en: "Education assistant",
          es: "Asistente de educación",
          fr: "Assistant d'éducation",
          ja: "教育アシスタント",
          ko: "교육 조수",
          pt: "Assistente de educação",
          tw: "教育助理",
          vi: "Trợ lý giáo dục",
          zh: "教育助理",
        },
        tool_count: 337,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 33636,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 6989,
      growth_rate: 0.2623,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "spikes-studio",
    name: "Spikes Studio",
    website: "https://spikes.studio",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169340886674173494.jpg",
    description:
      "Spikes helps creators extract captivating shorts from any video. Automatically get a title, description, hashtag recommendations, auto-captions, AI styling and quickly edit. Grow and give your audience more of you for a fraction of the time and cost!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 3,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "the-5-day-video-sprint-ai-youtube",
    name: "The 5-Day Video Sprint (AI + YouTube)",
    website: "https://make5videos.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169322534745756085.jpg",
    description:
      "You'll Create 5 Videos in 5 Days. Break the Cycle of Procrastination. Make a bet with yourself! ❌ No Overthinking. ❌ No Second-guessing. ❌ No Fancy editing or camera tricks",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "klipme",
    name: "Klipme",
    website: "https://klipmeapp.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169295779451788045.jpg",
    description:
      "Klipme is an AI video editor designed to streamline the editing process. Have AI analyze your longer videos and choose the best moments for a competition. Up your promotion or social media game with AI content.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "social-media-assistant",
        name: "Social media assistant",
        name_locales: {
          de: "Social-Media-Assistent",
          en: "Social media assistant",
          es: "Asistente de redes sociales",
          fr: "Assistant de médias sociaux",
          ja: "ソーシャルメディアアシスタント",
          ko: "소셜미디어 어시스턴트",
          pt: "Assistente de mídia social",
          tw: "社交媒體助理",
          vi: "Trợ lý truyền thông xã hội",
          zh: "社交媒体助理",
        },
        tool_count: 396,
      },
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 3136,
    collected_count: 5,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 2181,
      growth_rate: 2.2838,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "blogmyvideo",
    name: "BlogMyVideo",
    website: "https://blogmyvideo.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169253850466444800.jpg",
    description:
      "Automatically Transform your videos, audios, and podcasts into beautifully crafted blogs and articles. Elevate their discoverability on search engines and captivate a wider audience through the power of AI-driven transformation.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "seo",
        name: "SEO",
        name_locales: {
          de: "SEO",
          en: "SEO",
          es: "SEO",
          fr: "SEO",
          ja: "検索エンジン最適化",
          ko: "검색 엔진 최적화",
          pt: "SEO",
          tw: "搜尋引擎最佳化",
          vi: "tối ưu hóa công cụ tìm kiếm",
          zh: "搜索引擎优化",
        },
        tool_count: 264,
      },
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 3,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "askvideo-ai",
    name: "AskVideo.ai",
    website: "https://www.askvideo.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169228013479090700.jpg",
    description:
      "From training tutorials to recorded webinars, AskVideo.ai infuses your videos with AI brilliance. Pose questions, obtain highlights, extract insights, and delve deeper—all within your video content.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "education-assistant",
        name: "Education assistant",
        name_locales: {
          de: "Bildungsassistent",
          en: "Education assistant",
          es: "Asistente de educación",
          fr: "Assistant d'éducation",
          ja: "教育アシスタント",
          ko: "교육 조수",
          pt: "Assistente de educação",
          tw: "教育助理",
          vi: "Trợ lý giáo dục",
          zh: "教育助理",
        },
        tool_count: 337,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "ai-watcher-pro",
    name: "AI Watcher PRO",
    website: "https://www.aiwatcher.pro",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169220591533583489.jpg",
    description:
      "AWP tracks thematic sets of channels on YouTube. AWP crafts exclusive, brief textual digests of videos just for you. AWP translates and summarizes video content, distilling the key ideas and insights.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "summarizer",
        name: "Summarizer",
        name_locales: {
          de: "Summarizer",
          en: "Summarizer",
          es: "Generador de resúmenes",
          fr: "Résumeur",
          ja: "要約作成ツール",
          ko: "요약 생성기",
          pt: "Resumidor",
          tw: "摘要產生器",
          vi: "Trình tóm tắt",
          zh: "摘要生成器",
        },
        tool_count: 196,
      },
      {
        handle: "personalized-videos",
        name: "Personalized videos",
        name_locales: {
          de: "Personalisierte Videos",
          en: "Personalized videos",
          es: "Videos personalizados",
          fr: "Vidéos personnalisées",
          ja: "パーソナライズ動画",
          ko: "맞춤형 비디오",
          pt: "Vídeos personalizados",
          tw: "個人化影片",
          vi: "Video cá nhân hóa",
          zh: "个性化视频",
        },
        tool_count: 129,
      },
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 1468,
    collected_count: 4,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 847,
      growth_rate: 1.3639,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "gling-ai",
    name: "Gling AI",
    website: "https://gling.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169218836773048951.jpg",
    description:
      "Gling harnesses the power of cutting-edge AI technology to automatically identify and eliminate silences and unwanted takes from your videos. No more manual cutting, trimming, or endless editing sessions – Gling does it all for you!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "audio-editing",
        name: "Audio editing",
        name_locales: {
          de: "Audiobearbeitung",
          en: "Audio editing",
          es: "Edición de audio",
          fr: "Montage audio",
          ja: "オーディオ編集",
          ko: "오디오 편집",
          pt: "Edição de áudio",
          tw: "音訊編輯",
          vi: "Chỉnh sửa âm thanh",
          zh: "音频编辑",
        },
        tool_count: 109,
      },
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 91161,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.3448247300134665,
      top_traffic_sources: [
        {
          title: "Search",
          value: 0.3928603305976329,
        },
        {
          title: "Direct",
          value: 0.30247301721627207,
        },
        {
          title: "Social",
          value: 0.2163032958332251,
        },
      ],
      growth: 7241,
      growth_rate: 0.0863,
      monthly_visits_mail: 0,
      monthly_visits_direct: 27574,
      monthly_visits_search: 35814,
      monthly_visits_social: 19718,
      monthly_visits_referrals: 8055,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "videosum",
    name: "Videosum",
    website: "https://www.Videosum.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169166822233932456.jpg",
    description:
      "A revolutionary platform using AI for video processing. Key features include automated transcriptions, effortless captions & subtitles, engaging social media posts, and an intuitive user interface. Transform video interaction with state-of-the-art technology.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "voiceling",
    name: "Voiceling",
    website: "https://voiceling.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169141185121119170.jpg",
    description:
      "Voiceling is an AI-driven Chrome Extension that enables YouTube dubbing and translation to videos. Enjoy videos in 30+ languages with realistic voiceovers, gender recognition, multi-speaker detection, and background noise conservation.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
      {
        handle: "language-learning",
        name: "Language learning",
        name_locales: {
          de: "Sprachenlernen",
          en: "Language learning",
          es: "Aprendizaje de idiomas",
          fr: "Apprentissage des langues",
          ja: "言語学習",
          ko: "언어 학습",
          pt: "Aprendizagem de idiomas",
          tw: "語言學習",
          vi: "Học ngôn ngữ",
          zh: "语言学习",
        },
        tool_count: 235,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 1635,
    collected_count: 3,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 1566,
      growth_rate: 22.6957,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "illustory-studio",
    name: "Illustory Studio",
    website: "https://illustory.studio",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169134153894505561.jpg",
    description:
      "A Collaborative Platform that targets multimedia industries specifically storytelling. Starting from scripting to making multimedia such as graphical novels, anime and animations, and even 3D VR animations ( metaverse ).",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "art",
        name: "Art",
        name_locales: {
          de: "Kunst",
          en: "Art",
          es: "Arte",
          fr: "Art",
          ja: "芸術",
          ko: "예술",
          pt: "Arte",
          tw: "藝術",
          vi: "Nghệ thuật",
          zh: "艺术",
        },
        tool_count: 398,
      },
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "taja-ai",
    name: "Taja AI",
    website: "https://taja.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169116424443182828.jpg",
    description:
      "Taja is an AI-Powered SEO expert designed specifically for content creators with YouTube channels to assist with last mile publishing initiatives. Taja is here to revolutionize your YouTube growth strategy and help you unlock untapped potential!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "seo",
        name: "SEO",
        name_locales: {
          de: "SEO",
          en: "SEO",
          es: "SEO",
          fr: "SEO",
          ja: "検索エンジン最適化",
          ko: "검색 엔진 최적화",
          pt: "SEO",
          tw: "搜尋引擎最佳化",
          vi: "tối ưu hóa công cụ tìm kiếm",
          zh: "搜索引擎优化",
        },
        tool_count: 264,
      },
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 30974,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 30702,
      growth_rate: 112.875,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "edit-on-the-spot",
    name: "Edit on the Spot",
    website: "https://editonthespot.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169107000553422141.jpg",
    description:
      "Edit on the Spot automates video editing for content creators and large event tech companies. We capture the live feed while the videos are recorded and edit in real-time using AI.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 1144,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 315,
      growth_rate: 0.38,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "qr-tube",
    name: "QR-Tube",
    website: "https://qr-tube.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169098402242518232.jpg",
    description:
      "Process to add QR code to YouTube videos in order to increase click on YouTube on TV. Simple process, just add custom link form which you want to create QR code select coupe of options, select desired video and add start time and duration. And you are done.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "webralia",
    name: "Webralia",
    website: "https://webralia.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169089654550136454.jpg",
    description:
      "Webralia: Where AI Meets Inspiration! Elevate your content game with our AI Writer's 200+ templates, Chatbot Assistant, AI Image Wizard, Coding Companion, Speech-to-Text Sorcery, and Enchanting Voiceover.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "copywriting",
        name: "Copywriting",
        name_locales: {
          de: "Copywriting",
          en: "Copywriting",
          es: "Redacción publicitaria",
          fr: "L'écriture publicitaire",
          ja: "コピーライティング",
          ko: "콘텐츠 제작",
          pt: "Redação publicitária",
          tw: "文案寫作",
          vi: "Viết quảng cáo",
          zh: "文案写作",
        },
        tool_count: 435,
      },
      {
        handle: "image-editing",
        name: "Image editing",
        name_locales: {
          de: "Bildbearbeitung",
          en: "Image editing",
          es: "Edición de imágenes",
          fr: "Édition d'images",
          ja: "画像編集",
          ko: "이미지 편집",
          pt: "Edição de imagem",
          tw: "影像編輯",
          vi: "Chỉnh sửa ảnh",
          zh: "影像编辑",
        },
        tool_count: 221,
      },
      {
        handle: "text-to-speech",
        name: "Text to speech",
        name_locales: {
          de: "Text-zu-Sprache",
          en: "Text to speech",
          es: "Texto a voz",
          fr: "Texte à parole",
          ja: "テキスト読み上げ",
          ko: "문장 읽어주기",
          pt: "Texto para fala",
          tw: "文本轉語音",
          vi: "Văn bản thành giọng nói",
          zh: "文本转语音",
        },
        tool_count: 181,
      },
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "unidub-co",
    name: "UniDub.co",
    website: "https://unidub.co",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169053861759596547.jpg",
    description:
      "UniDub.co is a Multi-lingual AI Dubbing platform that can create or dub videos, Audiobooks, podcasts, and YouTube videos in 45+ languages with the original actors / own voice, emotions, and background music.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "audio-editing",
        name: "Audio editing",
        name_locales: {
          de: "Audiobearbeitung",
          en: "Audio editing",
          es: "Edición de audio",
          fr: "Montage audio",
          ja: "オーディオ編集",
          ko: "오디오 편집",
          pt: "Edição de áudio",
          tw: "音訊編輯",
          vi: "Chỉnh sửa âm thanh",
          zh: "音频编辑",
        },
        tool_count: 109,
      },
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "language-learning",
        name: "Language learning",
        name_locales: {
          de: "Sprachenlernen",
          en: "Language learning",
          es: "Aprendizaje de idiomas",
          fr: "Apprentissage des langues",
          ja: "言語学習",
          ko: "언어 학습",
          pt: "Aprendizagem de idiomas",
          tw: "語言學習",
          vi: "Học ngôn ngữ",
          zh: "语言学习",
        },
        tool_count: 235,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 2706,
    collected_count: 4,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: -359,
      growth_rate: -0.1171,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "motionscape",
    name: "MotionScape",
    website: "https://www.motionscape.co",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/169010634889241885.jpg",
    description:
      "MotionScape bypasses the lengthy and costly process of contracting freelancers and hiring employees and provides B2B brands with a simple and more affordable way to acquire converting content for their business with just a click of a button!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "sales",
        name: "Sales",
        name_locales: {
          de: "Verkauf",
          en: "Sales",
          es: "Venta",
          fr: "Vente",
          ja: "セールス",
          ko: "판매",
          pt: "Vendas",
          tw: "銷售",
          vi: "Bán hàng",
          zh: "销售",
        },
        tool_count: 158,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 0,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: null,
      growth_rate: null,
      monthly_visits_mail: null,
      monthly_visits_direct: null,
      monthly_visits_search: null,
      monthly_visits_social: null,
      monthly_visits_referrals: null,
      monthly_visits_paid_referrals: null,
      region_monthly_visits: null,
    },
  },
  {
    handle: "trimmr-ai",
    name: "trimmr.ai",
    website: "https://www.trimmr.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168917907978216888.jpg",
    description:
      "Trimmr is an AI-powered application that shortens long YouTube videos into shareable clips by identifying the most interesting or relevant segments of a video. It helps content creators produce viral videos that capture viewers' attention.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "ai-chatbots",
        name: "AI Chatbots",
        name_locales: {
          de: "AI-Chatbots",
          en: "AI Chatbots",
          es: "Chatbots de IA",
          fr: "Chatbots d'IA",
          ja: "AIチャットボット",
          ko: "AI 챗봇",
          pt: "Chatbots de IA",
          tw: "人工智能聊天機器人",
          vi: "Trò chuyện với Chatbots AI",
          zh: "人工智能聊天机器人",
        },
        tool_count: 2421,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 19099,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: -15839,
      growth_rate: -0.4533,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "hirevire",
    name: "Hirevire",
    website: "https://hirevire.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168917901861887700.jpg",
    description:
      "Are you wasting time interviewing candidates you're never going to hire? Hirevire's automated screening software lets you collect video, audio and file responses from candidates. Join hundreds of companies that have enhanced their screening and hiring process.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "human-resources",
        name: "Human resources",
        name_locales: {
          de: "Personalwesen",
          en: "Human resources",
          es: "Recursos humanos",
          fr: "Ressources humaines",
          ja: "人事",
          ko: "인사",
          pt: "Recursos humanos",
          tw: "人力資源",
          vi: "Nhân sự",
          zh: "人力资源",
        },
        tool_count: 147,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 24040,
    collected_count: 3,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 11813,
      growth_rate: 0.9661,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "ai-webcam-effects-for-video-meetings",
    name: "AI Webcam Effects for Video Meetings",
    website: "https://webcameffects.ai",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168863778779480761.jpg",
    description:
      "Enhance video calls like never before! Our extension offers virtual backgrounds, blur, beautification, auto-framing, color correction, lower thirds, emojis and more. Perfect for many communication platforms. Elevate your presence today.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "productivity",
        name: "Productivity",
        name_locales: {
          de: "Produktivität",
          en: "Productivity",
          es: "Productividad",
          fr: "Productivité",
          ja: "生産性",
          ko: "생산성",
          pt: "Produtividade",
          tw: "生產力",
          vi: "Năng suất",
          zh: "生产力",
        },
        tool_count: 775,
      },
      {
        handle: "ai-content-detector",
        name: "AI Content Detector",
        name_locales: {
          de: "AI-Detektor",
          en: "AI Content Detector",
          es: "Detector de IA",
          fr: "Détecteur d'IA",
          ja: "AI検出器",
          ko: "인공지능 감지기",
          pt: "Detector de IA",
          tw: "AI檢測器",
          vi: "Bộ phát hiện trí tuệ nhân tạo",
          zh: "人工智能检测器",
        },
        tool_count: 489,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 23586,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 16261,
      growth_rate: 2.2199,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "talkvisions",
    name: "TalkVisions",
    website: "https://talkvisions.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168863775662060892.jpg",
    description:
      "Introducing TalkVisions, a ground-breaking mobile application that eliminates language barriers by offering in-video closed captioning translations. See what you say, with TalkVisions.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "transcriber",
        name: "Transcriber",
        name_locales: {
          de: "Transkriptor",
          en: "Transcriber",
          es: "Transcriptor",
          fr: "Transcripteur",
          ja: "音声認識者",
          ko: "전사자",
          pt: "Transcritor",
          tw: "轉錄員",
          vi: "Người chuyển văn bản",
          zh: "转录员",
        },
        tool_count: 134,
      },
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "language-learning",
        name: "Language learning",
        name_locales: {
          de: "Sprachenlernen",
          en: "Language learning",
          es: "Aprendizaje de idiomas",
          fr: "Apprentissage des langues",
          ja: "言語学習",
          ko: "언어 학습",
          pt: "Aprendizagem de idiomas",
          tw: "語言學習",
          vi: "Học ngôn ngữ",
          zh: "语言学习",
        },
        tool_count: 235,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 1706,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 385,
      growth_rate: 0.2914,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "imagineapp",
    name: "Imagineapp",
    website: "https://imagineapp.co",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168812898440157020.jpg",
    description:
      "ImagineApp is where dreams come to life! We've created a platform that lets you transform video content in astonishing ways. Train any character in any style - the only limit is your imagination. Check out our YouTube promo for a taste of the magic!",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "art",
        name: "Art",
        name_locales: {
          de: "Kunst",
          en: "Art",
          es: "Arte",
          fr: "Art",
          ja: "芸術",
          ko: "예술",
          pt: "Arte",
          tw: "藝術",
          vi: "Nghệ thuật",
          zh: "艺术",
        },
        tool_count: 398,
      },
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 11905,
    collected_count: 10,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 7707,
      growth_rate: 1.8359,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "youtube-transcripts-by-editby-ai",
    name: "Youtube transcripts by Editby.ai",
    website: "https://www.transcriptdownload.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168804555491313854.jpg",
    description:
      "Easily convert your YouTube videos to text. With our free YouTube transcription tool, you can create accurate transcripts and captions. Navigate to specific video positions and read the entire transcript.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "transcriber",
        name: "Transcriber",
        name_locales: {
          de: "Transkriptor",
          en: "Transcriber",
          es: "Transcriptor",
          fr: "Transcripteur",
          ja: "音声認識者",
          ko: "전사자",
          pt: "Transcritor",
          tw: "轉錄員",
          vi: "Người chuyển văn bản",
          zh: "转录员",
        },
        tool_count: 134,
      },
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 31448,
    collected_count: 5,
    user_collected: 0,
    traffic: {
      top_region: "US",
      top_region_value: 0.3407547781581816,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.6250884910932363,
        },
        {
          title: "Referrals",
          value: 0.21061235515401855,
        },
        {
          title: "Social",
          value: 0.16007128300690926,
        },
      ],
      growth: 22440,
      growth_rate: 2.4911,
      monthly_visits_mail: 0,
      monthly_visits_direct: 19658,
      monthly_visits_search: 133,
      monthly_visits_social: 5034,
      monthly_visits_referrals: 6623,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "speakmulti",
    name: "Speakmulti",
    website: "https://speakmulti.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168803973084463498.jpg",
    description:
      "🌐 Convert YouTube videos into multiple languages with authentic speaker voices. 🗣️",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "language-learning",
        name: "Language learning",
        name_locales: {
          de: "Sprachenlernen",
          en: "Language learning",
          es: "Aprendizaje de idiomas",
          fr: "Apprentissage des langues",
          ja: "言語学習",
          ko: "언어 학습",
          pt: "Aprendizagem de idiomas",
          tw: "語言學習",
          vi: "Học ngôn ngữ",
          zh: "语言学习",
        },
        tool_count: 235,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 1084,
    collected_count: 2,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 1084,
      growth_rate: 0,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "reccloud",
    name: "RecCloud",
    website: "https://reccloud.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168803971883779285.jpg",
    description:
      "RecCloud, which is a free multifunctional online application, is dedicated to providing users with comprehensive video recording and editing services. In addition, we also offer various AI tools including Chatvideo, AI speech-to-text, AI subtitles.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 191803,
    collected_count: 1,
    user_collected: 0,
    traffic: {
      top_region: "BR",
      top_region_value: 0.18746287198413492,
      top_traffic_sources: [
        {
          title: "Direct",
          value: 0.508646209184945,
        },
        {
          title: "Referrals",
          value: 0.3313779712542492,
        },
        {
          title: "Social",
          value: 0.09804589195079008,
        },
      ],
      growth: 83014,
      growth_rate: 0.7631,
      monthly_visits_mail: 694,
      monthly_visits_direct: 97560,
      monthly_visits_search: 11185,
      monthly_visits_social: 18805,
      monthly_visits_referrals: 63559,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "video-highlight-clip-and-transcript-api",
    name: "Video Highlight, Clip and Transcript API",
    website: "https://www.contentgroove.com",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168750947242535980.jpg",
    description:
      "Upload video or audio files from URL or disk. Get a clean, accurate transcript without filler words and a set of NLP-suggested video clips along with timestamps and corresponding auto-generated titles. Sign-up for our app to see this API in action.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "transcriber",
        name: "Transcriber",
        name_locales: {
          de: "Transkriptor",
          en: "Transcriber",
          es: "Transcriptor",
          fr: "Transcripteur",
          ja: "音声認識者",
          ko: "전사자",
          pt: "Transcritor",
          tw: "轉錄員",
          vi: "Người chuyển văn bản",
          zh: "转录员",
        },
        tool_count: 134,
      },
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 25695,
    collected_count: 5,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 3047,
      growth_rate: 0.1345,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
  {
    handle: "langswap-app-a-video-translator-tool",
    name: "Langswap.app - a video translator tool",
    website: "https://langswap.app",
    image:
      "https://nav-station.oss-accelerate.aliyuncs.com/168718102959458635.jpg",
    description:
      "Langswap is a video localization tool that helps content creators reach global audiences. With our Speech recognition and Voice Cloning technologies, you can translate and voiceover your videos in minutes, without hiring a voice actor.",
    description_locales: null,
    review: null,
    categories: [
      {
        handle: "video-editing",
        name: "Video editing",
        name_locales: {
          de: "Videobearbeitung",
          en: "Video editing",
          es: "Edición de vídeo",
          fr: "Montage vidéo",
          ja: "ビデオ編集",
          ko: "비디오 편집",
          pt: "Edição de vídeo",
          tw: "影片剪輯",
          vi: "Chỉnh sửa video",
          zh: "视频剪辑",
        },
        tool_count: 114,
      },
      {
        handle: "language-learning",
        name: "Language learning",
        name_locales: {
          de: "Sprachenlernen",
          en: "Language learning",
          es: "Aprendizaje de idiomas",
          fr: "Apprentissage des langues",
          ja: "言語学習",
          ko: "언어 학습",
          pt: "Aprendizagem de idiomas",
          tw: "語言學習",
          vi: "Học ngôn ngữ",
          zh: "语言学习",
        },
        tool_count: 235,
      },
    ],
    attributes: [
      {
        handle: "features",
        name: "Features",
        options: [
          {
            name: "Website",
            handle: "website",
          },
        ],
      },
    ],
    prices: null,
    month_visited_count: 7069,
    collected_count: 4,
    user_collected: 0,
    traffic: {
      top_region: null,
      top_region_value: null,
      top_traffic_sources: [],
      growth: 6901,
      growth_rate: 41.0774,
      monthly_visits_mail: 0,
      monthly_visits_direct: 0,
      monthly_visits_search: 0,
      monthly_visits_social: 0,
      monthly_visits_referrals: 0,
      monthly_visits_paid_referrals: 0,
      region_monthly_visits: null,
    },
  },
];
